// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="Application_Application,hls_ip_2022_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=1,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7a35t-cpg236-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=7.287000,HLS_SYN_LAT=-1,HLS_SYN_TPT=none,HLS_SYN_MEM=16,HLS_SYN_DSP=0,HLS_SYN_FF=9438,HLS_SYN_LUT=14494,HLS_VERSION=2022_2}" *)

module Application (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        grayscale,
        brighten,
        flip,
        invert,
        sepia,
        sharpen,
        amount1,
        amount2,
        ap_return
);

parameter    ap_ST_fsm_state1 = 45'd1;
parameter    ap_ST_fsm_state2 = 45'd2;
parameter    ap_ST_fsm_state3 = 45'd4;
parameter    ap_ST_fsm_state4 = 45'd8;
parameter    ap_ST_fsm_state5 = 45'd16;
parameter    ap_ST_fsm_state6 = 45'd32;
parameter    ap_ST_fsm_state7 = 45'd64;
parameter    ap_ST_fsm_state8 = 45'd128;
parameter    ap_ST_fsm_state9 = 45'd256;
parameter    ap_ST_fsm_state10 = 45'd512;
parameter    ap_ST_fsm_state11 = 45'd1024;
parameter    ap_ST_fsm_state12 = 45'd2048;
parameter    ap_ST_fsm_state13 = 45'd4096;
parameter    ap_ST_fsm_state14 = 45'd8192;
parameter    ap_ST_fsm_state15 = 45'd16384;
parameter    ap_ST_fsm_state16 = 45'd32768;
parameter    ap_ST_fsm_state17 = 45'd65536;
parameter    ap_ST_fsm_state18 = 45'd131072;
parameter    ap_ST_fsm_state19 = 45'd262144;
parameter    ap_ST_fsm_state20 = 45'd524288;
parameter    ap_ST_fsm_state21 = 45'd1048576;
parameter    ap_ST_fsm_state22 = 45'd2097152;
parameter    ap_ST_fsm_state23 = 45'd4194304;
parameter    ap_ST_fsm_state24 = 45'd8388608;
parameter    ap_ST_fsm_state25 = 45'd16777216;
parameter    ap_ST_fsm_state26 = 45'd33554432;
parameter    ap_ST_fsm_state27 = 45'd67108864;
parameter    ap_ST_fsm_state28 = 45'd134217728;
parameter    ap_ST_fsm_state29 = 45'd268435456;
parameter    ap_ST_fsm_state30 = 45'd536870912;
parameter    ap_ST_fsm_state31 = 45'd1073741824;
parameter    ap_ST_fsm_state32 = 45'd2147483648;
parameter    ap_ST_fsm_state33 = 45'd4294967296;
parameter    ap_ST_fsm_state34 = 45'd8589934592;
parameter    ap_ST_fsm_state35 = 45'd17179869184;
parameter    ap_ST_fsm_state36 = 45'd34359738368;
parameter    ap_ST_fsm_state37 = 45'd68719476736;
parameter    ap_ST_fsm_state38 = 45'd137438953472;
parameter    ap_ST_fsm_state39 = 45'd274877906944;
parameter    ap_ST_fsm_state40 = 45'd549755813888;
parameter    ap_ST_fsm_state41 = 45'd1099511627776;
parameter    ap_ST_fsm_state42 = 45'd2199023255552;
parameter    ap_ST_fsm_state43 = 45'd4398046511104;
parameter    ap_ST_fsm_state44 = 45'd8796093022208;
parameter    ap_ST_fsm_state45 = 45'd17592186044416;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [31:0] grayscale;
input  [31:0] brighten;
input  [31:0] flip;
input  [31:0] invert;
input  [31:0] sepia;
input  [31:0] sharpen;
input  [31:0] amount1;
input  [31:0] amount2;
output  [31:0] ap_return;

reg ap_done;
reg ap_idle;
reg ap_ready;

(* fsm_encoding = "none" *) reg   [44:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [31:0] grp_fu_232_p2;
reg   [31:0] reg_260;
wire    ap_CS_fsm_state21;
wire    ap_CS_fsm_state28;
wire    ap_CS_fsm_state2;
wire   [31:0] grp_p_hls_fptosi_float_i32_fu_180_ap_return;
reg   [31:0] flipHorizontal_reg_461;
wire   [31:0] grp_p_hls_fptosi_float_i32_fu_186_ap_return;
reg   [31:0] flipVertical_reg_466;
wire   [0:0] icmp_ln83_fu_266_p2;
reg   [0:0] icmp_ln83_reg_471;
wire   [0:0] icmp_ln98_fu_272_p2;
reg   [0:0] icmp_ln98_reg_475;
wire    ap_CS_fsm_state4;
wire   [31:0] grp_fu_238_p2;
reg   [31:0] mul_reg_479;
wire    ap_CS_fsm_state7;
wire   [0:0] brmerge_demorgan_fu_318_p2;
reg   [0:0] brmerge_demorgan_reg_484;
wire   [0:0] icmp_ln137_fu_325_p2;
reg   [0:0] icmp_ln137_reg_489;
wire    ap_CS_fsm_state8;
wire   [0:0] icmp_ln139_fu_330_p2;
reg   [0:0] icmp_ln139_reg_493;
reg   [11:0] phi_mul_load_reg_511;
wire    ap_CS_fsm_state9;
wire   [0:0] icmp_ln164_fu_380_p2;
reg   [0:0] icmp_ln164_reg_519;
wire   [0:0] icmp_ln141_fu_358_p2;
reg   [6:0] i_4_reg_530;
wire    ap_CS_fsm_state11;
wire   [0:0] icmp_ln182_fu_411_p2;
reg   [0:0] icmp_ln182_reg_538;
wire   [0:0] icmp_ln166_fu_394_p2;
wire   [0:0] icmp_ln195_fu_416_p2;
reg   [0:0] icmp_ln195_reg_542;
wire    ap_CS_fsm_state13;
wire   [0:0] icmp_ln212_fu_421_p2;
reg   [0:0] icmp_ln212_reg_546;
wire    ap_CS_fsm_state15;
wire   [31:0] grp_fu_244_p2;
reg   [31:0] factor_reg_550;
wire    ap_CS_fsm_state44;
reg   [11:0] image_address0;
reg    image_ce0;
reg    image_we0;
reg   [31:0] image_d0;
wire   [31:0] image_q0;
reg   [11:0] image_address1;
reg    image_ce1;
reg    image_we1;
reg   [31:0] image_d1;
wire   [31:0] image_q1;
wire    grp_Application_Pipeline_VITIS_LOOP_61_1_fu_172_ap_start;
wire    grp_Application_Pipeline_VITIS_LOOP_61_1_fu_172_ap_done;
wire    grp_Application_Pipeline_VITIS_LOOP_61_1_fu_172_ap_idle;
wire    grp_Application_Pipeline_VITIS_LOOP_61_1_fu_172_ap_ready;
wire   [11:0] grp_Application_Pipeline_VITIS_LOOP_61_1_fu_172_image_r_address0;
wire    grp_Application_Pipeline_VITIS_LOOP_61_1_fu_172_image_r_ce0;
wire    grp_Application_Pipeline_VITIS_LOOP_61_1_fu_172_image_r_we0;
wire   [31:0] grp_Application_Pipeline_VITIS_LOOP_61_1_fu_172_image_r_d0;
reg   [31:0] grp_p_hls_fptosi_float_i32_fu_180_x;
reg    grp_p_hls_fptosi_float_i32_fu_180_ap_ce;
reg    grp_p_hls_fptosi_float_i32_fu_186_ap_ce;
wire    grp_Application_Pipeline_VITIS_LOOP_85_2_VITIS_LOOP_87_3_fu_192_ap_start;
wire    grp_Application_Pipeline_VITIS_LOOP_85_2_VITIS_LOOP_87_3_fu_192_ap_done;
wire    grp_Application_Pipeline_VITIS_LOOP_85_2_VITIS_LOOP_87_3_fu_192_ap_idle;
wire    grp_Application_Pipeline_VITIS_LOOP_85_2_VITIS_LOOP_87_3_fu_192_ap_ready;
wire   [11:0] grp_Application_Pipeline_VITIS_LOOP_85_2_VITIS_LOOP_87_3_fu_192_image_r_address0;
wire    grp_Application_Pipeline_VITIS_LOOP_85_2_VITIS_LOOP_87_3_fu_192_image_r_ce0;
wire    grp_Application_Pipeline_VITIS_LOOP_85_2_VITIS_LOOP_87_3_fu_192_image_r_we0;
wire   [31:0] grp_Application_Pipeline_VITIS_LOOP_85_2_VITIS_LOOP_87_3_fu_192_image_r_d0;
wire   [11:0] grp_Application_Pipeline_VITIS_LOOP_85_2_VITIS_LOOP_87_3_fu_192_image_r_address1;
wire    grp_Application_Pipeline_VITIS_LOOP_85_2_VITIS_LOOP_87_3_fu_192_image_r_ce1;
wire    grp_Application_Pipeline_VITIS_LOOP_85_2_VITIS_LOOP_87_3_fu_192_image_r_we1;
wire   [31:0] grp_Application_Pipeline_VITIS_LOOP_85_2_VITIS_LOOP_87_3_fu_192_image_r_d1;
wire   [63:0] grp_Application_Pipeline_VITIS_LOOP_85_2_VITIS_LOOP_87_3_fu_192_grp_fu_555_p_din0;
wire   [63:0] grp_Application_Pipeline_VITIS_LOOP_85_2_VITIS_LOOP_87_3_fu_192_grp_fu_555_p_din1;
wire   [1:0] grp_Application_Pipeline_VITIS_LOOP_85_2_VITIS_LOOP_87_3_fu_192_grp_fu_555_p_opcode;
wire    grp_Application_Pipeline_VITIS_LOOP_85_2_VITIS_LOOP_87_3_fu_192_grp_fu_555_p_ce;
wire   [63:0] grp_Application_Pipeline_VITIS_LOOP_85_2_VITIS_LOOP_87_3_fu_192_grp_fu_559_p_din0;
wire   [63:0] grp_Application_Pipeline_VITIS_LOOP_85_2_VITIS_LOOP_87_3_fu_192_grp_fu_559_p_din1;
wire    grp_Application_Pipeline_VITIS_LOOP_85_2_VITIS_LOOP_87_3_fu_192_grp_fu_559_p_ce;
wire   [31:0] grp_Application_Pipeline_VITIS_LOOP_85_2_VITIS_LOOP_87_3_fu_192_grp_fu_563_p_din0;
wire    grp_Application_Pipeline_VITIS_LOOP_85_2_VITIS_LOOP_87_3_fu_192_grp_fu_563_p_ce;
wire    grp_Application_Pipeline_VITIS_LOOP_100_4_VITIS_LOOP_102_5_fu_197_ap_start;
wire    grp_Application_Pipeline_VITIS_LOOP_100_4_VITIS_LOOP_102_5_fu_197_ap_done;
wire    grp_Application_Pipeline_VITIS_LOOP_100_4_VITIS_LOOP_102_5_fu_197_ap_idle;
wire    grp_Application_Pipeline_VITIS_LOOP_100_4_VITIS_LOOP_102_5_fu_197_ap_ready;
wire   [11:0] grp_Application_Pipeline_VITIS_LOOP_100_4_VITIS_LOOP_102_5_fu_197_image_r_address0;
wire    grp_Application_Pipeline_VITIS_LOOP_100_4_VITIS_LOOP_102_5_fu_197_image_r_ce0;
wire    grp_Application_Pipeline_VITIS_LOOP_100_4_VITIS_LOOP_102_5_fu_197_image_r_we0;
wire   [31:0] grp_Application_Pipeline_VITIS_LOOP_100_4_VITIS_LOOP_102_5_fu_197_image_r_d0;
wire   [11:0] grp_Application_Pipeline_VITIS_LOOP_100_4_VITIS_LOOP_102_5_fu_197_image_r_address1;
wire    grp_Application_Pipeline_VITIS_LOOP_100_4_VITIS_LOOP_102_5_fu_197_image_r_ce1;
wire    grp_Application_Pipeline_VITIS_LOOP_100_4_VITIS_LOOP_102_5_fu_197_image_r_we1;
wire   [31:0] grp_Application_Pipeline_VITIS_LOOP_100_4_VITIS_LOOP_102_5_fu_197_image_r_d1;
wire   [31:0] grp_Application_Pipeline_VITIS_LOOP_100_4_VITIS_LOOP_102_5_fu_197_grp_fu_232_p_din0;
wire   [31:0] grp_Application_Pipeline_VITIS_LOOP_100_4_VITIS_LOOP_102_5_fu_197_grp_fu_232_p_din1;
wire   [1:0] grp_Application_Pipeline_VITIS_LOOP_100_4_VITIS_LOOP_102_5_fu_197_grp_fu_232_p_opcode;
wire    grp_Application_Pipeline_VITIS_LOOP_100_4_VITIS_LOOP_102_5_fu_197_grp_fu_232_p_ce;
wire   [31:0] grp_Application_Pipeline_VITIS_LOOP_100_4_VITIS_LOOP_102_5_fu_197_grp_fu_566_p_din0;
wire    grp_Application_Pipeline_VITIS_LOOP_100_4_VITIS_LOOP_102_5_fu_197_grp_fu_566_p_ce;
wire   [31:0] grp_Application_Pipeline_VITIS_LOOP_100_4_VITIS_LOOP_102_5_fu_197_grp_p_hls_fptosi_float_i32_fu_180_p_din1;
wire    grp_Application_Pipeline_VITIS_LOOP_100_4_VITIS_LOOP_102_5_fu_197_grp_p_hls_fptosi_float_i32_fu_180_p_ce;
wire    grp_Application_Pipeline_VITIS_LOOP_145_7_fu_204_ap_start;
wire    grp_Application_Pipeline_VITIS_LOOP_145_7_fu_204_ap_done;
wire    grp_Application_Pipeline_VITIS_LOOP_145_7_fu_204_ap_idle;
wire    grp_Application_Pipeline_VITIS_LOOP_145_7_fu_204_ap_ready;
wire   [11:0] grp_Application_Pipeline_VITIS_LOOP_145_7_fu_204_image_r_address0;
wire    grp_Application_Pipeline_VITIS_LOOP_145_7_fu_204_image_r_ce0;
wire    grp_Application_Pipeline_VITIS_LOOP_145_7_fu_204_image_r_we0;
wire   [31:0] grp_Application_Pipeline_VITIS_LOOP_145_7_fu_204_image_r_d0;
wire   [11:0] grp_Application_Pipeline_VITIS_LOOP_145_7_fu_204_image_r_address1;
wire    grp_Application_Pipeline_VITIS_LOOP_145_7_fu_204_image_r_ce1;
wire    grp_Application_Pipeline_VITIS_LOOP_145_7_fu_204_image_r_we1;
wire   [31:0] grp_Application_Pipeline_VITIS_LOOP_145_7_fu_204_image_r_d1;
wire    grp_Application_Pipeline_VITIS_LOOP_170_9_fu_210_ap_start;
wire    grp_Application_Pipeline_VITIS_LOOP_170_9_fu_210_ap_done;
wire    grp_Application_Pipeline_VITIS_LOOP_170_9_fu_210_ap_idle;
wire    grp_Application_Pipeline_VITIS_LOOP_170_9_fu_210_ap_ready;
wire   [11:0] grp_Application_Pipeline_VITIS_LOOP_170_9_fu_210_image_r_address0;
wire    grp_Application_Pipeline_VITIS_LOOP_170_9_fu_210_image_r_ce0;
wire    grp_Application_Pipeline_VITIS_LOOP_170_9_fu_210_image_r_we0;
wire   [31:0] grp_Application_Pipeline_VITIS_LOOP_170_9_fu_210_image_r_d0;
wire   [11:0] grp_Application_Pipeline_VITIS_LOOP_170_9_fu_210_image_r_address1;
wire    grp_Application_Pipeline_VITIS_LOOP_170_9_fu_210_image_r_ce1;
wire    grp_Application_Pipeline_VITIS_LOOP_184_10_VITIS_LOOP_186_11_fu_216_ap_start;
wire    grp_Application_Pipeline_VITIS_LOOP_184_10_VITIS_LOOP_186_11_fu_216_ap_done;
wire    grp_Application_Pipeline_VITIS_LOOP_184_10_VITIS_LOOP_186_11_fu_216_ap_idle;
wire    grp_Application_Pipeline_VITIS_LOOP_184_10_VITIS_LOOP_186_11_fu_216_ap_ready;
wire   [11:0] grp_Application_Pipeline_VITIS_LOOP_184_10_VITIS_LOOP_186_11_fu_216_image_r_address0;
wire    grp_Application_Pipeline_VITIS_LOOP_184_10_VITIS_LOOP_186_11_fu_216_image_r_ce0;
wire    grp_Application_Pipeline_VITIS_LOOP_184_10_VITIS_LOOP_186_11_fu_216_image_r_we0;
wire   [31:0] grp_Application_Pipeline_VITIS_LOOP_184_10_VITIS_LOOP_186_11_fu_216_image_r_d0;
wire   [11:0] grp_Application_Pipeline_VITIS_LOOP_184_10_VITIS_LOOP_186_11_fu_216_image_r_address1;
wire    grp_Application_Pipeline_VITIS_LOOP_184_10_VITIS_LOOP_186_11_fu_216_image_r_ce1;
wire    grp_Application_Pipeline_VITIS_LOOP_184_10_VITIS_LOOP_186_11_fu_216_image_r_we1;
wire   [31:0] grp_Application_Pipeline_VITIS_LOOP_184_10_VITIS_LOOP_186_11_fu_216_image_r_d1;
wire    grp_Application_Pipeline_VITIS_LOOP_197_12_VITIS_LOOP_199_13_fu_221_ap_start;
wire    grp_Application_Pipeline_VITIS_LOOP_197_12_VITIS_LOOP_199_13_fu_221_ap_done;
wire    grp_Application_Pipeline_VITIS_LOOP_197_12_VITIS_LOOP_199_13_fu_221_ap_idle;
wire    grp_Application_Pipeline_VITIS_LOOP_197_12_VITIS_LOOP_199_13_fu_221_ap_ready;
wire   [11:0] grp_Application_Pipeline_VITIS_LOOP_197_12_VITIS_LOOP_199_13_fu_221_image_r_address0;
wire    grp_Application_Pipeline_VITIS_LOOP_197_12_VITIS_LOOP_199_13_fu_221_image_r_ce0;
wire    grp_Application_Pipeline_VITIS_LOOP_197_12_VITIS_LOOP_199_13_fu_221_image_r_we0;
wire   [31:0] grp_Application_Pipeline_VITIS_LOOP_197_12_VITIS_LOOP_199_13_fu_221_image_r_d0;
wire   [11:0] grp_Application_Pipeline_VITIS_LOOP_197_12_VITIS_LOOP_199_13_fu_221_image_r_address1;
wire    grp_Application_Pipeline_VITIS_LOOP_197_12_VITIS_LOOP_199_13_fu_221_image_r_ce1;
wire    grp_Application_Pipeline_VITIS_LOOP_197_12_VITIS_LOOP_199_13_fu_221_image_r_we1;
wire   [31:0] grp_Application_Pipeline_VITIS_LOOP_197_12_VITIS_LOOP_199_13_fu_221_image_r_d1;
wire   [63:0] grp_Application_Pipeline_VITIS_LOOP_197_12_VITIS_LOOP_199_13_fu_221_grp_fu_555_p_din0;
wire   [63:0] grp_Application_Pipeline_VITIS_LOOP_197_12_VITIS_LOOP_199_13_fu_221_grp_fu_555_p_din1;
wire   [1:0] grp_Application_Pipeline_VITIS_LOOP_197_12_VITIS_LOOP_199_13_fu_221_grp_fu_555_p_opcode;
wire    grp_Application_Pipeline_VITIS_LOOP_197_12_VITIS_LOOP_199_13_fu_221_grp_fu_555_p_ce;
wire   [63:0] grp_Application_Pipeline_VITIS_LOOP_197_12_VITIS_LOOP_199_13_fu_221_grp_fu_559_p_din0;
wire   [63:0] grp_Application_Pipeline_VITIS_LOOP_197_12_VITIS_LOOP_199_13_fu_221_grp_fu_559_p_din1;
wire    grp_Application_Pipeline_VITIS_LOOP_197_12_VITIS_LOOP_199_13_fu_221_grp_fu_559_p_ce;
wire   [31:0] grp_Application_Pipeline_VITIS_LOOP_197_12_VITIS_LOOP_199_13_fu_221_grp_fu_563_p_din0;
wire    grp_Application_Pipeline_VITIS_LOOP_197_12_VITIS_LOOP_199_13_fu_221_grp_fu_563_p_ce;
wire    grp_Application_Pipeline_VITIS_LOOP_216_14_VITIS_LOOP_217_15_fu_226_ap_start;
wire    grp_Application_Pipeline_VITIS_LOOP_216_14_VITIS_LOOP_217_15_fu_226_ap_done;
wire    grp_Application_Pipeline_VITIS_LOOP_216_14_VITIS_LOOP_217_15_fu_226_ap_idle;
wire    grp_Application_Pipeline_VITIS_LOOP_216_14_VITIS_LOOP_217_15_fu_226_ap_ready;
wire   [11:0] grp_Application_Pipeline_VITIS_LOOP_216_14_VITIS_LOOP_217_15_fu_226_image_r_address0;
wire    grp_Application_Pipeline_VITIS_LOOP_216_14_VITIS_LOOP_217_15_fu_226_image_r_ce0;
wire    grp_Application_Pipeline_VITIS_LOOP_216_14_VITIS_LOOP_217_15_fu_226_image_r_we0;
wire   [31:0] grp_Application_Pipeline_VITIS_LOOP_216_14_VITIS_LOOP_217_15_fu_226_image_r_d0;
wire   [11:0] grp_Application_Pipeline_VITIS_LOOP_216_14_VITIS_LOOP_217_15_fu_226_image_r_address1;
wire    grp_Application_Pipeline_VITIS_LOOP_216_14_VITIS_LOOP_217_15_fu_226_image_r_ce1;
wire    grp_Application_Pipeline_VITIS_LOOP_216_14_VITIS_LOOP_217_15_fu_226_image_r_we1;
wire   [31:0] grp_Application_Pipeline_VITIS_LOOP_216_14_VITIS_LOOP_217_15_fu_226_image_r_d1;
wire   [31:0] grp_Application_Pipeline_VITIS_LOOP_216_14_VITIS_LOOP_217_15_fu_226_grp_fu_232_p_din0;
wire   [31:0] grp_Application_Pipeline_VITIS_LOOP_216_14_VITIS_LOOP_217_15_fu_226_grp_fu_232_p_din1;
wire   [1:0] grp_Application_Pipeline_VITIS_LOOP_216_14_VITIS_LOOP_217_15_fu_226_grp_fu_232_p_opcode;
wire    grp_Application_Pipeline_VITIS_LOOP_216_14_VITIS_LOOP_217_15_fu_226_grp_fu_232_p_ce;
wire   [31:0] grp_Application_Pipeline_VITIS_LOOP_216_14_VITIS_LOOP_217_15_fu_226_grp_fu_238_p_din0;
wire   [31:0] grp_Application_Pipeline_VITIS_LOOP_216_14_VITIS_LOOP_217_15_fu_226_grp_fu_238_p_din1;
wire    grp_Application_Pipeline_VITIS_LOOP_216_14_VITIS_LOOP_217_15_fu_226_grp_fu_238_p_ce;
wire   [31:0] grp_Application_Pipeline_VITIS_LOOP_216_14_VITIS_LOOP_217_15_fu_226_grp_fu_566_p_din0;
wire    grp_Application_Pipeline_VITIS_LOOP_216_14_VITIS_LOOP_217_15_fu_226_grp_fu_566_p_ce;
wire   [31:0] grp_Application_Pipeline_VITIS_LOOP_216_14_VITIS_LOOP_217_15_fu_226_grp_p_hls_fptosi_float_i32_fu_180_p_din1;
wire    grp_Application_Pipeline_VITIS_LOOP_216_14_VITIS_LOOP_217_15_fu_226_grp_p_hls_fptosi_float_i32_fu_180_p_ce;
reg    grp_Application_Pipeline_VITIS_LOOP_61_1_fu_172_ap_start_reg;
reg    grp_Application_Pipeline_VITIS_LOOP_85_2_VITIS_LOOP_87_3_fu_192_ap_start_reg;
wire    ap_CS_fsm_state3;
reg    grp_Application_Pipeline_VITIS_LOOP_100_4_VITIS_LOOP_102_5_fu_197_ap_start_reg;
reg    grp_Application_Pipeline_VITIS_LOOP_145_7_fu_204_ap_start_reg;
wire    ap_CS_fsm_state10;
reg    grp_Application_Pipeline_VITIS_LOOP_170_9_fu_210_ap_start_reg;
wire    ap_CS_fsm_state12;
reg    grp_Application_Pipeline_VITIS_LOOP_184_10_VITIS_LOOP_186_11_fu_216_ap_start_reg;
reg    grp_Application_Pipeline_VITIS_LOOP_197_12_VITIS_LOOP_199_13_fu_221_ap_start_reg;
wire    ap_CS_fsm_state14;
reg    grp_Application_Pipeline_VITIS_LOOP_216_14_VITIS_LOOP_217_15_fu_226_ap_start_reg;
wire    ap_CS_fsm_state45;
reg   [11:0] phi_mul_fu_112;
wire   [11:0] add_ln141_1_fu_352_p2;
reg    ap_block_state8_on_subcall_done;
reg   [4:0] i_fu_116;
wire   [4:0] add_ln141_fu_364_p2;
reg   [6:0] i_3_fu_120;
wire   [6:0] add_ln166_fu_400_p2;
reg   [31:0] grp_fu_232_p0;
reg   [31:0] grp_fu_232_p1;
wire    ap_CS_fsm_state22;
reg   [31:0] grp_fu_238_p0;
reg   [31:0] grp_fu_238_p1;
wire    ap_CS_fsm_state29;
wire    ap_CS_fsm_state6;
wire   [31:0] amount1_to_int_fu_277_p1;
wire   [7:0] tmp_fu_280_p4;
wire   [22:0] empty_fu_290_p1;
wire   [0:0] notrhs_fu_300_p2;
wire   [0:0] notlhs_fu_294_p2;
wire   [0:0] empty_66_fu_306_p2;
wire   [0:0] grp_fu_250_p2;
wire   [0:0] empty_67_fu_312_p2;
wire   [0:0] grp_fu_255_p2;
reg    grp_fu_232_ce;
reg    ap_block_state15_on_subcall_done;
wire    ap_CS_fsm_state16;
wire    ap_CS_fsm_state17;
wire    ap_CS_fsm_state18;
wire    ap_CS_fsm_state19;
wire    ap_CS_fsm_state20;
wire    ap_CS_fsm_state23;
wire    ap_CS_fsm_state24;
wire    ap_CS_fsm_state25;
wire    ap_CS_fsm_state26;
wire    ap_CS_fsm_state27;
reg    grp_fu_238_ce;
reg    ap_block_state4_on_subcall_done;
wire    ap_CS_fsm_state5;
reg    ap_block_state13_on_subcall_done;
wire   [63:0] grp_fu_555_p2;
reg   [63:0] grp_fu_555_p0;
reg   [63:0] grp_fu_555_p1;
reg    grp_fu_555_ce;
wire   [63:0] grp_fu_559_p2;
reg   [63:0] grp_fu_559_p0;
reg   [63:0] grp_fu_559_p1;
reg    grp_fu_559_ce;
wire   [63:0] grp_fu_563_p1;
reg   [31:0] grp_fu_563_p0;
reg    grp_fu_563_ce;
wire   [31:0] grp_fu_566_p1;
reg   [31:0] grp_fu_566_p0;
reg    grp_fu_566_ce;
reg    ap_block_state45_on_subcall_done;
reg   [44:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
reg    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
reg    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
reg    ap_ST_fsm_state8_blk;
wire    ap_ST_fsm_state9_blk;
reg    ap_ST_fsm_state10_blk;
wire    ap_ST_fsm_state11_blk;
reg    ap_ST_fsm_state12_blk;
reg    ap_ST_fsm_state13_blk;
wire    ap_ST_fsm_state14_blk;
reg    ap_ST_fsm_state15_blk;
wire    ap_ST_fsm_state16_blk;
wire    ap_ST_fsm_state17_blk;
wire    ap_ST_fsm_state18_blk;
wire    ap_ST_fsm_state19_blk;
wire    ap_ST_fsm_state20_blk;
wire    ap_ST_fsm_state21_blk;
wire    ap_ST_fsm_state22_blk;
wire    ap_ST_fsm_state23_blk;
wire    ap_ST_fsm_state24_blk;
wire    ap_ST_fsm_state25_blk;
wire    ap_ST_fsm_state26_blk;
wire    ap_ST_fsm_state27_blk;
wire    ap_ST_fsm_state28_blk;
wire    ap_ST_fsm_state29_blk;
wire    ap_ST_fsm_state30_blk;
wire    ap_ST_fsm_state31_blk;
wire    ap_ST_fsm_state32_blk;
wire    ap_ST_fsm_state33_blk;
wire    ap_ST_fsm_state34_blk;
wire    ap_ST_fsm_state35_blk;
wire    ap_ST_fsm_state36_blk;
wire    ap_ST_fsm_state37_blk;
wire    ap_ST_fsm_state38_blk;
wire    ap_ST_fsm_state39_blk;
wire    ap_ST_fsm_state40_blk;
wire    ap_ST_fsm_state41_blk;
wire    ap_ST_fsm_state42_blk;
wire    ap_ST_fsm_state43_blk;
wire    ap_ST_fsm_state44_blk;
reg    ap_ST_fsm_state45_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 45'd1;
#0 grp_Application_Pipeline_VITIS_LOOP_61_1_fu_172_ap_start_reg = 1'b0;
#0 grp_Application_Pipeline_VITIS_LOOP_85_2_VITIS_LOOP_87_3_fu_192_ap_start_reg = 1'b0;
#0 grp_Application_Pipeline_VITIS_LOOP_100_4_VITIS_LOOP_102_5_fu_197_ap_start_reg = 1'b0;
#0 grp_Application_Pipeline_VITIS_LOOP_145_7_fu_204_ap_start_reg = 1'b0;
#0 grp_Application_Pipeline_VITIS_LOOP_170_9_fu_210_ap_start_reg = 1'b0;
#0 grp_Application_Pipeline_VITIS_LOOP_184_10_VITIS_LOOP_186_11_fu_216_ap_start_reg = 1'b0;
#0 grp_Application_Pipeline_VITIS_LOOP_197_12_VITIS_LOOP_199_13_fu_221_ap_start_reg = 1'b0;
#0 grp_Application_Pipeline_VITIS_LOOP_216_14_VITIS_LOOP_217_15_fu_226_ap_start_reg = 1'b0;
end

Application_image_RAM_AUTO_1R1W #(
    .DataWidth( 32 ),
    .AddressRange( 2070 ),
    .AddressWidth( 12 ))
image_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(image_address0),
    .ce0(image_ce0),
    .we0(image_we0),
    .d0(image_d0),
    .q0(image_q0),
    .address1(image_address1),
    .ce1(image_ce1),
    .we1(image_we1),
    .d1(image_d1),
    .q1(image_q1)
);

Application_Application_Pipeline_VITIS_LOOP_61_1 grp_Application_Pipeline_VITIS_LOOP_61_1_fu_172(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_Application_Pipeline_VITIS_LOOP_61_1_fu_172_ap_start),
    .ap_done(grp_Application_Pipeline_VITIS_LOOP_61_1_fu_172_ap_done),
    .ap_idle(grp_Application_Pipeline_VITIS_LOOP_61_1_fu_172_ap_idle),
    .ap_ready(grp_Application_Pipeline_VITIS_LOOP_61_1_fu_172_ap_ready),
    .image_r_address0(grp_Application_Pipeline_VITIS_LOOP_61_1_fu_172_image_r_address0),
    .image_r_ce0(grp_Application_Pipeline_VITIS_LOOP_61_1_fu_172_image_r_ce0),
    .image_r_we0(grp_Application_Pipeline_VITIS_LOOP_61_1_fu_172_image_r_we0),
    .image_r_d0(grp_Application_Pipeline_VITIS_LOOP_61_1_fu_172_image_r_d0)
);

Application_p_hls_fptosi_float_i32 grp_p_hls_fptosi_float_i32_fu_180(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .x(grp_p_hls_fptosi_float_i32_fu_180_x),
    .ap_return(grp_p_hls_fptosi_float_i32_fu_180_ap_return),
    .ap_ce(grp_p_hls_fptosi_float_i32_fu_180_ap_ce)
);

Application_p_hls_fptosi_float_i32 grp_p_hls_fptosi_float_i32_fu_186(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .x(amount2),
    .ap_return(grp_p_hls_fptosi_float_i32_fu_186_ap_return),
    .ap_ce(grp_p_hls_fptosi_float_i32_fu_186_ap_ce)
);

Application_Application_Pipeline_VITIS_LOOP_85_2_VITIS_LOOP_87_3 grp_Application_Pipeline_VITIS_LOOP_85_2_VITIS_LOOP_87_3_fu_192(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_Application_Pipeline_VITIS_LOOP_85_2_VITIS_LOOP_87_3_fu_192_ap_start),
    .ap_done(grp_Application_Pipeline_VITIS_LOOP_85_2_VITIS_LOOP_87_3_fu_192_ap_done),
    .ap_idle(grp_Application_Pipeline_VITIS_LOOP_85_2_VITIS_LOOP_87_3_fu_192_ap_idle),
    .ap_ready(grp_Application_Pipeline_VITIS_LOOP_85_2_VITIS_LOOP_87_3_fu_192_ap_ready),
    .image_r_address0(grp_Application_Pipeline_VITIS_LOOP_85_2_VITIS_LOOP_87_3_fu_192_image_r_address0),
    .image_r_ce0(grp_Application_Pipeline_VITIS_LOOP_85_2_VITIS_LOOP_87_3_fu_192_image_r_ce0),
    .image_r_we0(grp_Application_Pipeline_VITIS_LOOP_85_2_VITIS_LOOP_87_3_fu_192_image_r_we0),
    .image_r_d0(grp_Application_Pipeline_VITIS_LOOP_85_2_VITIS_LOOP_87_3_fu_192_image_r_d0),
    .image_r_q0(image_q0),
    .image_r_address1(grp_Application_Pipeline_VITIS_LOOP_85_2_VITIS_LOOP_87_3_fu_192_image_r_address1),
    .image_r_ce1(grp_Application_Pipeline_VITIS_LOOP_85_2_VITIS_LOOP_87_3_fu_192_image_r_ce1),
    .image_r_we1(grp_Application_Pipeline_VITIS_LOOP_85_2_VITIS_LOOP_87_3_fu_192_image_r_we1),
    .image_r_d1(grp_Application_Pipeline_VITIS_LOOP_85_2_VITIS_LOOP_87_3_fu_192_image_r_d1),
    .image_r_q1(image_q1),
    .grp_fu_555_p_din0(grp_Application_Pipeline_VITIS_LOOP_85_2_VITIS_LOOP_87_3_fu_192_grp_fu_555_p_din0),
    .grp_fu_555_p_din1(grp_Application_Pipeline_VITIS_LOOP_85_2_VITIS_LOOP_87_3_fu_192_grp_fu_555_p_din1),
    .grp_fu_555_p_opcode(grp_Application_Pipeline_VITIS_LOOP_85_2_VITIS_LOOP_87_3_fu_192_grp_fu_555_p_opcode),
    .grp_fu_555_p_dout0(grp_fu_555_p2),
    .grp_fu_555_p_ce(grp_Application_Pipeline_VITIS_LOOP_85_2_VITIS_LOOP_87_3_fu_192_grp_fu_555_p_ce),
    .grp_fu_559_p_din0(grp_Application_Pipeline_VITIS_LOOP_85_2_VITIS_LOOP_87_3_fu_192_grp_fu_559_p_din0),
    .grp_fu_559_p_din1(grp_Application_Pipeline_VITIS_LOOP_85_2_VITIS_LOOP_87_3_fu_192_grp_fu_559_p_din1),
    .grp_fu_559_p_dout0(grp_fu_559_p2),
    .grp_fu_559_p_ce(grp_Application_Pipeline_VITIS_LOOP_85_2_VITIS_LOOP_87_3_fu_192_grp_fu_559_p_ce),
    .grp_fu_563_p_din0(grp_Application_Pipeline_VITIS_LOOP_85_2_VITIS_LOOP_87_3_fu_192_grp_fu_563_p_din0),
    .grp_fu_563_p_dout0(grp_fu_563_p1),
    .grp_fu_563_p_ce(grp_Application_Pipeline_VITIS_LOOP_85_2_VITIS_LOOP_87_3_fu_192_grp_fu_563_p_ce)
);

Application_Application_Pipeline_VITIS_LOOP_100_4_VITIS_LOOP_102_5 grp_Application_Pipeline_VITIS_LOOP_100_4_VITIS_LOOP_102_5_fu_197(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_Application_Pipeline_VITIS_LOOP_100_4_VITIS_LOOP_102_5_fu_197_ap_start),
    .ap_done(grp_Application_Pipeline_VITIS_LOOP_100_4_VITIS_LOOP_102_5_fu_197_ap_done),
    .ap_idle(grp_Application_Pipeline_VITIS_LOOP_100_4_VITIS_LOOP_102_5_fu_197_ap_idle),
    .ap_ready(grp_Application_Pipeline_VITIS_LOOP_100_4_VITIS_LOOP_102_5_fu_197_ap_ready),
    .image_r_address0(grp_Application_Pipeline_VITIS_LOOP_100_4_VITIS_LOOP_102_5_fu_197_image_r_address0),
    .image_r_ce0(grp_Application_Pipeline_VITIS_LOOP_100_4_VITIS_LOOP_102_5_fu_197_image_r_ce0),
    .image_r_we0(grp_Application_Pipeline_VITIS_LOOP_100_4_VITIS_LOOP_102_5_fu_197_image_r_we0),
    .image_r_d0(grp_Application_Pipeline_VITIS_LOOP_100_4_VITIS_LOOP_102_5_fu_197_image_r_d0),
    .image_r_q0(image_q0),
    .image_r_address1(grp_Application_Pipeline_VITIS_LOOP_100_4_VITIS_LOOP_102_5_fu_197_image_r_address1),
    .image_r_ce1(grp_Application_Pipeline_VITIS_LOOP_100_4_VITIS_LOOP_102_5_fu_197_image_r_ce1),
    .image_r_we1(grp_Application_Pipeline_VITIS_LOOP_100_4_VITIS_LOOP_102_5_fu_197_image_r_we1),
    .image_r_d1(grp_Application_Pipeline_VITIS_LOOP_100_4_VITIS_LOOP_102_5_fu_197_image_r_d1),
    .image_r_q1(image_q1),
    .brmerge_demorgan(brmerge_demorgan_reg_484),
    .mul(mul_reg_479),
    .grp_fu_232_p_din0(grp_Application_Pipeline_VITIS_LOOP_100_4_VITIS_LOOP_102_5_fu_197_grp_fu_232_p_din0),
    .grp_fu_232_p_din1(grp_Application_Pipeline_VITIS_LOOP_100_4_VITIS_LOOP_102_5_fu_197_grp_fu_232_p_din1),
    .grp_fu_232_p_opcode(grp_Application_Pipeline_VITIS_LOOP_100_4_VITIS_LOOP_102_5_fu_197_grp_fu_232_p_opcode),
    .grp_fu_232_p_dout0(grp_fu_232_p2),
    .grp_fu_232_p_ce(grp_Application_Pipeline_VITIS_LOOP_100_4_VITIS_LOOP_102_5_fu_197_grp_fu_232_p_ce),
    .grp_fu_566_p_din0(grp_Application_Pipeline_VITIS_LOOP_100_4_VITIS_LOOP_102_5_fu_197_grp_fu_566_p_din0),
    .grp_fu_566_p_dout0(grp_fu_566_p1),
    .grp_fu_566_p_ce(grp_Application_Pipeline_VITIS_LOOP_100_4_VITIS_LOOP_102_5_fu_197_grp_fu_566_p_ce),
    .grp_p_hls_fptosi_float_i32_fu_180_p_din1(grp_Application_Pipeline_VITIS_LOOP_100_4_VITIS_LOOP_102_5_fu_197_grp_p_hls_fptosi_float_i32_fu_180_p_din1),
    .grp_p_hls_fptosi_float_i32_fu_180_p_dout0(grp_p_hls_fptosi_float_i32_fu_180_ap_return),
    .grp_p_hls_fptosi_float_i32_fu_180_p_ce(grp_Application_Pipeline_VITIS_LOOP_100_4_VITIS_LOOP_102_5_fu_197_grp_p_hls_fptosi_float_i32_fu_180_p_ce)
);

Application_Application_Pipeline_VITIS_LOOP_145_7 grp_Application_Pipeline_VITIS_LOOP_145_7_fu_204(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_Application_Pipeline_VITIS_LOOP_145_7_fu_204_ap_start),
    .ap_done(grp_Application_Pipeline_VITIS_LOOP_145_7_fu_204_ap_done),
    .ap_idle(grp_Application_Pipeline_VITIS_LOOP_145_7_fu_204_ap_idle),
    .ap_ready(grp_Application_Pipeline_VITIS_LOOP_145_7_fu_204_ap_ready),
    .phi_mul(phi_mul_load_reg_511),
    .image_r_address0(grp_Application_Pipeline_VITIS_LOOP_145_7_fu_204_image_r_address0),
    .image_r_ce0(grp_Application_Pipeline_VITIS_LOOP_145_7_fu_204_image_r_ce0),
    .image_r_we0(grp_Application_Pipeline_VITIS_LOOP_145_7_fu_204_image_r_we0),
    .image_r_d0(grp_Application_Pipeline_VITIS_LOOP_145_7_fu_204_image_r_d0),
    .image_r_q0(image_q0),
    .image_r_address1(grp_Application_Pipeline_VITIS_LOOP_145_7_fu_204_image_r_address1),
    .image_r_ce1(grp_Application_Pipeline_VITIS_LOOP_145_7_fu_204_image_r_ce1),
    .image_r_we1(grp_Application_Pipeline_VITIS_LOOP_145_7_fu_204_image_r_we1),
    .image_r_d1(grp_Application_Pipeline_VITIS_LOOP_145_7_fu_204_image_r_d1),
    .image_r_q1(image_q1)
);

Application_Application_Pipeline_VITIS_LOOP_170_9 grp_Application_Pipeline_VITIS_LOOP_170_9_fu_210(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_Application_Pipeline_VITIS_LOOP_170_9_fu_210_ap_start),
    .ap_done(grp_Application_Pipeline_VITIS_LOOP_170_9_fu_210_ap_done),
    .ap_idle(grp_Application_Pipeline_VITIS_LOOP_170_9_fu_210_ap_idle),
    .ap_ready(grp_Application_Pipeline_VITIS_LOOP_170_9_fu_210_ap_ready),
    .zext_ln166(i_4_reg_530),
    .image_r_address0(grp_Application_Pipeline_VITIS_LOOP_170_9_fu_210_image_r_address0),
    .image_r_ce0(grp_Application_Pipeline_VITIS_LOOP_170_9_fu_210_image_r_ce0),
    .image_r_we0(grp_Application_Pipeline_VITIS_LOOP_170_9_fu_210_image_r_we0),
    .image_r_d0(grp_Application_Pipeline_VITIS_LOOP_170_9_fu_210_image_r_d0),
    .image_r_q0(image_q0),
    .image_r_address1(grp_Application_Pipeline_VITIS_LOOP_170_9_fu_210_image_r_address1),
    .image_r_ce1(grp_Application_Pipeline_VITIS_LOOP_170_9_fu_210_image_r_ce1),
    .image_r_q1(image_q1)
);

Application_Application_Pipeline_VITIS_LOOP_184_10_VITIS_LOOP_186_11 grp_Application_Pipeline_VITIS_LOOP_184_10_VITIS_LOOP_186_11_fu_216(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_Application_Pipeline_VITIS_LOOP_184_10_VITIS_LOOP_186_11_fu_216_ap_start),
    .ap_done(grp_Application_Pipeline_VITIS_LOOP_184_10_VITIS_LOOP_186_11_fu_216_ap_done),
    .ap_idle(grp_Application_Pipeline_VITIS_LOOP_184_10_VITIS_LOOP_186_11_fu_216_ap_idle),
    .ap_ready(grp_Application_Pipeline_VITIS_LOOP_184_10_VITIS_LOOP_186_11_fu_216_ap_ready),
    .image_r_address0(grp_Application_Pipeline_VITIS_LOOP_184_10_VITIS_LOOP_186_11_fu_216_image_r_address0),
    .image_r_ce0(grp_Application_Pipeline_VITIS_LOOP_184_10_VITIS_LOOP_186_11_fu_216_image_r_ce0),
    .image_r_we0(grp_Application_Pipeline_VITIS_LOOP_184_10_VITIS_LOOP_186_11_fu_216_image_r_we0),
    .image_r_d0(grp_Application_Pipeline_VITIS_LOOP_184_10_VITIS_LOOP_186_11_fu_216_image_r_d0),
    .image_r_q0(image_q0),
    .image_r_address1(grp_Application_Pipeline_VITIS_LOOP_184_10_VITIS_LOOP_186_11_fu_216_image_r_address1),
    .image_r_ce1(grp_Application_Pipeline_VITIS_LOOP_184_10_VITIS_LOOP_186_11_fu_216_image_r_ce1),
    .image_r_we1(grp_Application_Pipeline_VITIS_LOOP_184_10_VITIS_LOOP_186_11_fu_216_image_r_we1),
    .image_r_d1(grp_Application_Pipeline_VITIS_LOOP_184_10_VITIS_LOOP_186_11_fu_216_image_r_d1),
    .image_r_q1(image_q1)
);

Application_Application_Pipeline_VITIS_LOOP_197_12_VITIS_LOOP_199_13 grp_Application_Pipeline_VITIS_LOOP_197_12_VITIS_LOOP_199_13_fu_221(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_Application_Pipeline_VITIS_LOOP_197_12_VITIS_LOOP_199_13_fu_221_ap_start),
    .ap_done(grp_Application_Pipeline_VITIS_LOOP_197_12_VITIS_LOOP_199_13_fu_221_ap_done),
    .ap_idle(grp_Application_Pipeline_VITIS_LOOP_197_12_VITIS_LOOP_199_13_fu_221_ap_idle),
    .ap_ready(grp_Application_Pipeline_VITIS_LOOP_197_12_VITIS_LOOP_199_13_fu_221_ap_ready),
    .image_r_address0(grp_Application_Pipeline_VITIS_LOOP_197_12_VITIS_LOOP_199_13_fu_221_image_r_address0),
    .image_r_ce0(grp_Application_Pipeline_VITIS_LOOP_197_12_VITIS_LOOP_199_13_fu_221_image_r_ce0),
    .image_r_we0(grp_Application_Pipeline_VITIS_LOOP_197_12_VITIS_LOOP_199_13_fu_221_image_r_we0),
    .image_r_d0(grp_Application_Pipeline_VITIS_LOOP_197_12_VITIS_LOOP_199_13_fu_221_image_r_d0),
    .image_r_q0(image_q0),
    .image_r_address1(grp_Application_Pipeline_VITIS_LOOP_197_12_VITIS_LOOP_199_13_fu_221_image_r_address1),
    .image_r_ce1(grp_Application_Pipeline_VITIS_LOOP_197_12_VITIS_LOOP_199_13_fu_221_image_r_ce1),
    .image_r_we1(grp_Application_Pipeline_VITIS_LOOP_197_12_VITIS_LOOP_199_13_fu_221_image_r_we1),
    .image_r_d1(grp_Application_Pipeline_VITIS_LOOP_197_12_VITIS_LOOP_199_13_fu_221_image_r_d1),
    .image_r_q1(image_q1),
    .grp_fu_555_p_din0(grp_Application_Pipeline_VITIS_LOOP_197_12_VITIS_LOOP_199_13_fu_221_grp_fu_555_p_din0),
    .grp_fu_555_p_din1(grp_Application_Pipeline_VITIS_LOOP_197_12_VITIS_LOOP_199_13_fu_221_grp_fu_555_p_din1),
    .grp_fu_555_p_opcode(grp_Application_Pipeline_VITIS_LOOP_197_12_VITIS_LOOP_199_13_fu_221_grp_fu_555_p_opcode),
    .grp_fu_555_p_dout0(grp_fu_555_p2),
    .grp_fu_555_p_ce(grp_Application_Pipeline_VITIS_LOOP_197_12_VITIS_LOOP_199_13_fu_221_grp_fu_555_p_ce),
    .grp_fu_559_p_din0(grp_Application_Pipeline_VITIS_LOOP_197_12_VITIS_LOOP_199_13_fu_221_grp_fu_559_p_din0),
    .grp_fu_559_p_din1(grp_Application_Pipeline_VITIS_LOOP_197_12_VITIS_LOOP_199_13_fu_221_grp_fu_559_p_din1),
    .grp_fu_559_p_dout0(grp_fu_559_p2),
    .grp_fu_559_p_ce(grp_Application_Pipeline_VITIS_LOOP_197_12_VITIS_LOOP_199_13_fu_221_grp_fu_559_p_ce),
    .grp_fu_563_p_din0(grp_Application_Pipeline_VITIS_LOOP_197_12_VITIS_LOOP_199_13_fu_221_grp_fu_563_p_din0),
    .grp_fu_563_p_dout0(grp_fu_563_p1),
    .grp_fu_563_p_ce(grp_Application_Pipeline_VITIS_LOOP_197_12_VITIS_LOOP_199_13_fu_221_grp_fu_563_p_ce)
);

Application_Application_Pipeline_VITIS_LOOP_216_14_VITIS_LOOP_217_15 grp_Application_Pipeline_VITIS_LOOP_216_14_VITIS_LOOP_217_15_fu_226(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_Application_Pipeline_VITIS_LOOP_216_14_VITIS_LOOP_217_15_fu_226_ap_start),
    .ap_done(grp_Application_Pipeline_VITIS_LOOP_216_14_VITIS_LOOP_217_15_fu_226_ap_done),
    .ap_idle(grp_Application_Pipeline_VITIS_LOOP_216_14_VITIS_LOOP_217_15_fu_226_ap_idle),
    .ap_ready(grp_Application_Pipeline_VITIS_LOOP_216_14_VITIS_LOOP_217_15_fu_226_ap_ready),
    .image_r_address0(grp_Application_Pipeline_VITIS_LOOP_216_14_VITIS_LOOP_217_15_fu_226_image_r_address0),
    .image_r_ce0(grp_Application_Pipeline_VITIS_LOOP_216_14_VITIS_LOOP_217_15_fu_226_image_r_ce0),
    .image_r_we0(grp_Application_Pipeline_VITIS_LOOP_216_14_VITIS_LOOP_217_15_fu_226_image_r_we0),
    .image_r_d0(grp_Application_Pipeline_VITIS_LOOP_216_14_VITIS_LOOP_217_15_fu_226_image_r_d0),
    .image_r_q0(image_q0),
    .image_r_address1(grp_Application_Pipeline_VITIS_LOOP_216_14_VITIS_LOOP_217_15_fu_226_image_r_address1),
    .image_r_ce1(grp_Application_Pipeline_VITIS_LOOP_216_14_VITIS_LOOP_217_15_fu_226_image_r_ce1),
    .image_r_we1(grp_Application_Pipeline_VITIS_LOOP_216_14_VITIS_LOOP_217_15_fu_226_image_r_we1),
    .image_r_d1(grp_Application_Pipeline_VITIS_LOOP_216_14_VITIS_LOOP_217_15_fu_226_image_r_d1),
    .image_r_q1(image_q1),
    .factor(factor_reg_550),
    .grp_fu_232_p_din0(grp_Application_Pipeline_VITIS_LOOP_216_14_VITIS_LOOP_217_15_fu_226_grp_fu_232_p_din0),
    .grp_fu_232_p_din1(grp_Application_Pipeline_VITIS_LOOP_216_14_VITIS_LOOP_217_15_fu_226_grp_fu_232_p_din1),
    .grp_fu_232_p_opcode(grp_Application_Pipeline_VITIS_LOOP_216_14_VITIS_LOOP_217_15_fu_226_grp_fu_232_p_opcode),
    .grp_fu_232_p_dout0(grp_fu_232_p2),
    .grp_fu_232_p_ce(grp_Application_Pipeline_VITIS_LOOP_216_14_VITIS_LOOP_217_15_fu_226_grp_fu_232_p_ce),
    .grp_fu_238_p_din0(grp_Application_Pipeline_VITIS_LOOP_216_14_VITIS_LOOP_217_15_fu_226_grp_fu_238_p_din0),
    .grp_fu_238_p_din1(grp_Application_Pipeline_VITIS_LOOP_216_14_VITIS_LOOP_217_15_fu_226_grp_fu_238_p_din1),
    .grp_fu_238_p_dout0(grp_fu_238_p2),
    .grp_fu_238_p_ce(grp_Application_Pipeline_VITIS_LOOP_216_14_VITIS_LOOP_217_15_fu_226_grp_fu_238_p_ce),
    .grp_fu_566_p_din0(grp_Application_Pipeline_VITIS_LOOP_216_14_VITIS_LOOP_217_15_fu_226_grp_fu_566_p_din0),
    .grp_fu_566_p_dout0(grp_fu_566_p1),
    .grp_fu_566_p_ce(grp_Application_Pipeline_VITIS_LOOP_216_14_VITIS_LOOP_217_15_fu_226_grp_fu_566_p_ce),
    .grp_p_hls_fptosi_float_i32_fu_180_p_din1(grp_Application_Pipeline_VITIS_LOOP_216_14_VITIS_LOOP_217_15_fu_226_grp_p_hls_fptosi_float_i32_fu_180_p_din1),
    .grp_p_hls_fptosi_float_i32_fu_180_p_dout0(grp_p_hls_fptosi_float_i32_fu_180_ap_return),
    .grp_p_hls_fptosi_float_i32_fu_180_p_ce(grp_Application_Pipeline_VITIS_LOOP_216_14_VITIS_LOOP_217_15_fu_226_grp_p_hls_fptosi_float_i32_fu_180_p_ce)
);

Application_fadd_32ns_32ns_32_7_full_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 7 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fadd_32ns_32ns_32_7_full_dsp_1_U46(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_232_p0),
    .din1(grp_fu_232_p1),
    .ce(grp_fu_232_ce),
    .dout(grp_fu_232_p2)
);

Application_fmul_32ns_32ns_32_4_max_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fmul_32ns_32ns_32_4_max_dsp_1_U47(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_238_p0),
    .din1(grp_fu_238_p1),
    .ce(grp_fu_238_ce),
    .dout(grp_fu_238_p2)
);

Application_fdiv_32ns_32ns_32_16_no_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 16 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fdiv_32ns_32ns_32_16_no_dsp_1_U48(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(reg_260),
    .din1(32'd1120403456),
    .ce(1'b1),
    .dout(grp_fu_244_p2)
);

Application_fcmp_32ns_32ns_1_2_no_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 1 ))
fcmp_32ns_32ns_1_2_no_dsp_1_U49(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(amount1),
    .din1(32'd3212836864),
    .ce(1'b1),
    .opcode(5'd3),
    .dout(grp_fu_250_p2)
);

Application_fcmp_32ns_32ns_1_2_no_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 1 ))
fcmp_32ns_32ns_1_2_no_dsp_1_U50(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(amount1),
    .din1(32'd1065353216),
    .ce(1'b1),
    .opcode(5'd5),
    .dout(grp_fu_255_p2)
);

Application_dadd_64ns_64ns_64_8_full_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 8 ),
    .din0_WIDTH( 64 ),
    .din1_WIDTH( 64 ),
    .dout_WIDTH( 64 ))
dadd_64ns_64ns_64_8_full_dsp_1_U51(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_555_p0),
    .din1(grp_fu_555_p1),
    .ce(grp_fu_555_ce),
    .dout(grp_fu_555_p2)
);

Application_dmul_64ns_64ns_64_7_max_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 7 ),
    .din0_WIDTH( 64 ),
    .din1_WIDTH( 64 ),
    .dout_WIDTH( 64 ))
dmul_64ns_64ns_64_7_max_dsp_1_U52(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_559_p0),
    .din1(grp_fu_559_p1),
    .ce(grp_fu_559_ce),
    .dout(grp_fu_559_p2)
);

Application_sitodp_32ns_64_6_no_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 6 ),
    .din0_WIDTH( 32 ),
    .dout_WIDTH( 64 ))
sitodp_32ns_64_6_no_dsp_1_U53(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_563_p0),
    .ce(grp_fu_563_ce),
    .dout(grp_fu_563_p1)
);

Application_sitofp_32ns_32_6_no_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 6 ),
    .din0_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
sitofp_32ns_32_6_no_dsp_1_U54(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_566_p0),
    .ce(grp_fu_566_ce),
    .dout(grp_fu_566_p1)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_Application_Pipeline_VITIS_LOOP_100_4_VITIS_LOOP_102_5_fu_197_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state7)) begin
            grp_Application_Pipeline_VITIS_LOOP_100_4_VITIS_LOOP_102_5_fu_197_ap_start_reg <= 1'b1;
        end else if ((grp_Application_Pipeline_VITIS_LOOP_100_4_VITIS_LOOP_102_5_fu_197_ap_ready == 1'b1)) begin
            grp_Application_Pipeline_VITIS_LOOP_100_4_VITIS_LOOP_102_5_fu_197_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_Application_Pipeline_VITIS_LOOP_145_7_fu_204_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state9) & (icmp_ln141_fu_358_p2 == 1'd0) & (icmp_ln139_reg_493 == 1'd0))) begin
            grp_Application_Pipeline_VITIS_LOOP_145_7_fu_204_ap_start_reg <= 1'b1;
        end else if ((grp_Application_Pipeline_VITIS_LOOP_145_7_fu_204_ap_ready == 1'b1)) begin
            grp_Application_Pipeline_VITIS_LOOP_145_7_fu_204_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_Application_Pipeline_VITIS_LOOP_170_9_fu_210_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state11) & (icmp_ln166_fu_394_p2 == 1'd0) & (icmp_ln164_reg_519 == 1'd0) & (icmp_ln137_reg_489 == 1'd0))) begin
            grp_Application_Pipeline_VITIS_LOOP_170_9_fu_210_ap_start_reg <= 1'b1;
        end else if ((grp_Application_Pipeline_VITIS_LOOP_170_9_fu_210_ap_ready == 1'b1)) begin
            grp_Application_Pipeline_VITIS_LOOP_170_9_fu_210_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_Application_Pipeline_VITIS_LOOP_184_10_VITIS_LOOP_186_11_fu_216_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state11) & ((((icmp_ln182_fu_411_p2 == 1'd0) & (icmp_ln164_reg_519 == 1'd1)) | ((icmp_ln166_fu_394_p2 == 1'd1) & (icmp_ln182_fu_411_p2 == 1'd0))) | ((icmp_ln182_fu_411_p2 == 1'd0) & (icmp_ln137_reg_489 == 1'd1))))) begin
            grp_Application_Pipeline_VITIS_LOOP_184_10_VITIS_LOOP_186_11_fu_216_ap_start_reg <= 1'b1;
        end else if ((grp_Application_Pipeline_VITIS_LOOP_184_10_VITIS_LOOP_186_11_fu_216_ap_ready == 1'b1)) begin
            grp_Application_Pipeline_VITIS_LOOP_184_10_VITIS_LOOP_186_11_fu_216_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_Application_Pipeline_VITIS_LOOP_197_12_VITIS_LOOP_199_13_fu_221_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state14)) begin
            grp_Application_Pipeline_VITIS_LOOP_197_12_VITIS_LOOP_199_13_fu_221_ap_start_reg <= 1'b1;
        end else if ((grp_Application_Pipeline_VITIS_LOOP_197_12_VITIS_LOOP_199_13_fu_221_ap_ready == 1'b1)) begin
            grp_Application_Pipeline_VITIS_LOOP_197_12_VITIS_LOOP_199_13_fu_221_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_Application_Pipeline_VITIS_LOOP_216_14_VITIS_LOOP_217_15_fu_226_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state44)) begin
            grp_Application_Pipeline_VITIS_LOOP_216_14_VITIS_LOOP_217_15_fu_226_ap_start_reg <= 1'b1;
        end else if ((grp_Application_Pipeline_VITIS_LOOP_216_14_VITIS_LOOP_217_15_fu_226_ap_ready == 1'b1)) begin
            grp_Application_Pipeline_VITIS_LOOP_216_14_VITIS_LOOP_217_15_fu_226_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_Application_Pipeline_VITIS_LOOP_61_1_fu_172_ap_start_reg <= 1'b0;
    end else begin
        if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
            grp_Application_Pipeline_VITIS_LOOP_61_1_fu_172_ap_start_reg <= 1'b1;
        end else if ((grp_Application_Pipeline_VITIS_LOOP_61_1_fu_172_ap_ready == 1'b1)) begin
            grp_Application_Pipeline_VITIS_LOOP_61_1_fu_172_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_Application_Pipeline_VITIS_LOOP_85_2_VITIS_LOOP_87_3_fu_192_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state3)) begin
            grp_Application_Pipeline_VITIS_LOOP_85_2_VITIS_LOOP_87_3_fu_192_ap_start_reg <= 1'b1;
        end else if ((grp_Application_Pipeline_VITIS_LOOP_85_2_VITIS_LOOP_87_3_fu_192_ap_ready == 1'b1)) begin
            grp_Application_Pipeline_VITIS_LOOP_85_2_VITIS_LOOP_87_3_fu_192_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state9) & (((icmp_ln164_fu_380_p2 == 1'd0) & (icmp_ln139_reg_493 == 1'd1)) | ((icmp_ln141_fu_358_p2 == 1'd1) & (icmp_ln164_fu_380_p2 == 1'd0))))) begin
        i_3_fu_120 <= 7'd0;
    end else if (((1'b1 == ap_CS_fsm_state11) & (icmp_ln166_fu_394_p2 == 1'd0) & (icmp_ln164_reg_519 == 1'd0) & (icmp_ln137_reg_489 == 1'd0))) begin
        i_3_fu_120 <= add_ln166_fu_400_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state8_on_subcall_done) & (1'b1 == ap_CS_fsm_state8) & (icmp_ln139_fu_330_p2 == 1'd0) & (icmp_ln137_fu_325_p2 == 1'd0))) begin
        i_fu_116 <= 5'd0;
    end else if (((1'b1 == ap_CS_fsm_state9) & (icmp_ln141_fu_358_p2 == 1'd0) & (icmp_ln139_reg_493 == 1'd0))) begin
        i_fu_116 <= add_ln141_fu_364_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state8_on_subcall_done) & (1'b1 == ap_CS_fsm_state8) & (icmp_ln139_fu_330_p2 == 1'd0) & (icmp_ln137_fu_325_p2 == 1'd0))) begin
        phi_mul_fu_112 <= 12'd0;
    end else if (((1'b1 == ap_CS_fsm_state9) & (icmp_ln141_fu_358_p2 == 1'd0) & (icmp_ln139_reg_493 == 1'd0))) begin
        phi_mul_fu_112 <= add_ln141_1_fu_352_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        brmerge_demorgan_reg_484 <= brmerge_demorgan_fu_318_p2;
        mul_reg_479 <= grp_fu_238_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state44)) begin
        factor_reg_550 <= grp_fu_244_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        flipHorizontal_reg_461 <= grp_p_hls_fptosi_float_i32_fu_180_ap_return;
        flipVertical_reg_466 <= grp_p_hls_fptosi_float_i32_fu_186_ap_return;
        icmp_ln83_reg_471 <= icmp_ln83_fu_266_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state11) & (icmp_ln164_reg_519 == 1'd0) & (icmp_ln137_reg_489 == 1'd0))) begin
        i_4_reg_530 <= i_3_fu_120;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        icmp_ln137_reg_489 <= icmp_ln137_fu_325_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state8) & (icmp_ln137_fu_325_p2 == 1'd0))) begin
        icmp_ln139_reg_493 <= icmp_ln139_fu_330_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state9) & ((icmp_ln141_fu_358_p2 == 1'd1) | (icmp_ln139_reg_493 == 1'd1)))) begin
        icmp_ln164_reg_519 <= icmp_ln164_fu_380_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state11) & ((icmp_ln137_reg_489 == 1'd1) | ((icmp_ln166_fu_394_p2 == 1'd1) | (icmp_ln164_reg_519 == 1'd1))))) begin
        icmp_ln182_reg_538 <= icmp_ln182_fu_411_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        icmp_ln195_reg_542 <= icmp_ln195_fu_416_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state15)) begin
        icmp_ln212_reg_546 <= icmp_ln212_fu_421_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        icmp_ln98_reg_475 <= icmp_ln98_fu_272_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state9) & (icmp_ln139_reg_493 == 1'd0))) begin
        phi_mul_load_reg_511 <= phi_mul_fu_112;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state28) | (1'b1 == ap_CS_fsm_state21))) begin
        reg_260 <= grp_fu_232_p2;
    end
end

always @ (*) begin
    if ((grp_Application_Pipeline_VITIS_LOOP_145_7_fu_204_ap_done == 1'b0)) begin
        ap_ST_fsm_state10_blk = 1'b1;
    end else begin
        ap_ST_fsm_state10_blk = 1'b0;
    end
end

assign ap_ST_fsm_state11_blk = 1'b0;

always @ (*) begin
    if ((grp_Application_Pipeline_VITIS_LOOP_170_9_fu_210_ap_done == 1'b0)) begin
        ap_ST_fsm_state12_blk = 1'b1;
    end else begin
        ap_ST_fsm_state12_blk = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state13_on_subcall_done)) begin
        ap_ST_fsm_state13_blk = 1'b1;
    end else begin
        ap_ST_fsm_state13_blk = 1'b0;
    end
end

assign ap_ST_fsm_state14_blk = 1'b0;

always @ (*) begin
    if ((1'b1 == ap_block_state15_on_subcall_done)) begin
        ap_ST_fsm_state15_blk = 1'b1;
    end else begin
        ap_ST_fsm_state15_blk = 1'b0;
    end
end

assign ap_ST_fsm_state16_blk = 1'b0;

assign ap_ST_fsm_state17_blk = 1'b0;

assign ap_ST_fsm_state18_blk = 1'b0;

assign ap_ST_fsm_state19_blk = 1'b0;

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state20_blk = 1'b0;

assign ap_ST_fsm_state21_blk = 1'b0;

assign ap_ST_fsm_state22_blk = 1'b0;

assign ap_ST_fsm_state23_blk = 1'b0;

assign ap_ST_fsm_state24_blk = 1'b0;

assign ap_ST_fsm_state25_blk = 1'b0;

assign ap_ST_fsm_state26_blk = 1'b0;

assign ap_ST_fsm_state27_blk = 1'b0;

assign ap_ST_fsm_state28_blk = 1'b0;

assign ap_ST_fsm_state29_blk = 1'b0;

always @ (*) begin
    if ((grp_Application_Pipeline_VITIS_LOOP_61_1_fu_172_ap_done == 1'b0)) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

assign ap_ST_fsm_state30_blk = 1'b0;

assign ap_ST_fsm_state31_blk = 1'b0;

assign ap_ST_fsm_state32_blk = 1'b0;

assign ap_ST_fsm_state33_blk = 1'b0;

assign ap_ST_fsm_state34_blk = 1'b0;

assign ap_ST_fsm_state35_blk = 1'b0;

assign ap_ST_fsm_state36_blk = 1'b0;

assign ap_ST_fsm_state37_blk = 1'b0;

assign ap_ST_fsm_state38_blk = 1'b0;

assign ap_ST_fsm_state39_blk = 1'b0;

assign ap_ST_fsm_state3_blk = 1'b0;

assign ap_ST_fsm_state40_blk = 1'b0;

assign ap_ST_fsm_state41_blk = 1'b0;

assign ap_ST_fsm_state42_blk = 1'b0;

assign ap_ST_fsm_state43_blk = 1'b0;

assign ap_ST_fsm_state44_blk = 1'b0;

always @ (*) begin
    if ((1'b1 == ap_block_state45_on_subcall_done)) begin
        ap_ST_fsm_state45_blk = 1'b1;
    end else begin
        ap_ST_fsm_state45_blk = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state4_on_subcall_done)) begin
        ap_ST_fsm_state4_blk = 1'b1;
    end else begin
        ap_ST_fsm_state4_blk = 1'b0;
    end
end

assign ap_ST_fsm_state5_blk = 1'b0;

assign ap_ST_fsm_state6_blk = 1'b0;

assign ap_ST_fsm_state7_blk = 1'b0;

always @ (*) begin
    if ((1'b1 == ap_block_state8_on_subcall_done)) begin
        ap_ST_fsm_state8_blk = 1'b1;
    end else begin
        ap_ST_fsm_state8_blk = 1'b0;
    end
end

assign ap_ST_fsm_state9_blk = 1'b0;

always @ (*) begin
    if (((1'b0 == ap_block_state45_on_subcall_done) & (1'b1 == ap_CS_fsm_state45))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state45_on_subcall_done) & (1'b1 == ap_CS_fsm_state45))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state45)) begin
        grp_fu_232_ce = grp_Application_Pipeline_VITIS_LOOP_216_14_VITIS_LOOP_217_15_fu_226_grp_fu_232_p_ce;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        grp_fu_232_ce = grp_Application_Pipeline_VITIS_LOOP_100_4_VITIS_LOOP_102_5_fu_197_grp_fu_232_p_ce;
    end else if (((1'b1 == ap_CS_fsm_state28) | (1'b1 == ap_CS_fsm_state21) | (1'b1 == ap_CS_fsm_state27) | (1'b1 == ap_CS_fsm_state26) | (1'b1 == ap_CS_fsm_state25) | (1'b1 == ap_CS_fsm_state24) | (1'b1 == ap_CS_fsm_state23) | (1'b1 == ap_CS_fsm_state20) | (1'b1 == ap_CS_fsm_state19) | (1'b1 == ap_CS_fsm_state18) | (1'b1 == ap_CS_fsm_state17) | (1'b1 == ap_CS_fsm_state16) | (1'b1 == ap_CS_fsm_state22) | ((1'b0 == ap_block_state15_on_subcall_done) & (1'b1 == ap_CS_fsm_state15)))) begin
        grp_fu_232_ce = 1'b1;
    end else begin
        grp_fu_232_ce = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state45)) begin
        grp_fu_232_p0 = grp_Application_Pipeline_VITIS_LOOP_216_14_VITIS_LOOP_217_15_fu_226_grp_fu_232_p_din0;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        grp_fu_232_p0 = grp_Application_Pipeline_VITIS_LOOP_100_4_VITIS_LOOP_102_5_fu_197_grp_fu_232_p_din0;
    end else if ((1'b1 == ap_CS_fsm_state22)) begin
        grp_fu_232_p0 = reg_260;
    end else if ((1'b1 == ap_CS_fsm_state15)) begin
        grp_fu_232_p0 = amount1;
    end else begin
        grp_fu_232_p0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state45)) begin
        grp_fu_232_p1 = grp_Application_Pipeline_VITIS_LOOP_216_14_VITIS_LOOP_217_15_fu_226_grp_fu_232_p_din1;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        grp_fu_232_p1 = grp_Application_Pipeline_VITIS_LOOP_100_4_VITIS_LOOP_102_5_fu_197_grp_fu_232_p_din1;
    end else if ((1'b1 == ap_CS_fsm_state22)) begin
        grp_fu_232_p1 = 32'd1120403456;
    end else if ((1'b1 == ap_CS_fsm_state15)) begin
        grp_fu_232_p1 = 32'd3259498496;
    end else begin
        grp_fu_232_p1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state45)) begin
        grp_fu_238_ce = grp_Application_Pipeline_VITIS_LOOP_216_14_VITIS_LOOP_217_15_fu_226_grp_fu_238_p_ce;
    end else if (((1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state7) | ((1'b0 == ap_block_state4_on_subcall_done) & (1'b1 == ap_CS_fsm_state4)))) begin
        grp_fu_238_ce = 1'b1;
    end else begin
        grp_fu_238_ce = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state45)) begin
        grp_fu_238_p0 = grp_Application_Pipeline_VITIS_LOOP_216_14_VITIS_LOOP_217_15_fu_226_grp_fu_238_p_din0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        grp_fu_238_p0 = amount1;
    end else begin
        grp_fu_238_p0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state45)) begin
        grp_fu_238_p1 = grp_Application_Pipeline_VITIS_LOOP_216_14_VITIS_LOOP_217_15_fu_226_grp_fu_238_p_din1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        grp_fu_238_p1 = 32'd1132396544;
    end else begin
        grp_fu_238_p1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state15)) begin
        grp_fu_555_ce = grp_Application_Pipeline_VITIS_LOOP_197_12_VITIS_LOOP_199_13_fu_221_grp_fu_555_p_ce;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        grp_fu_555_ce = grp_Application_Pipeline_VITIS_LOOP_85_2_VITIS_LOOP_87_3_fu_192_grp_fu_555_p_ce;
    end else begin
        grp_fu_555_ce = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state15)) begin
        grp_fu_555_p0 = grp_Application_Pipeline_VITIS_LOOP_197_12_VITIS_LOOP_199_13_fu_221_grp_fu_555_p_din0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        grp_fu_555_p0 = grp_Application_Pipeline_VITIS_LOOP_85_2_VITIS_LOOP_87_3_fu_192_grp_fu_555_p_din0;
    end else begin
        grp_fu_555_p0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state15)) begin
        grp_fu_555_p1 = grp_Application_Pipeline_VITIS_LOOP_197_12_VITIS_LOOP_199_13_fu_221_grp_fu_555_p_din1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        grp_fu_555_p1 = grp_Application_Pipeline_VITIS_LOOP_85_2_VITIS_LOOP_87_3_fu_192_grp_fu_555_p_din1;
    end else begin
        grp_fu_555_p1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state15)) begin
        grp_fu_559_ce = grp_Application_Pipeline_VITIS_LOOP_197_12_VITIS_LOOP_199_13_fu_221_grp_fu_559_p_ce;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        grp_fu_559_ce = grp_Application_Pipeline_VITIS_LOOP_85_2_VITIS_LOOP_87_3_fu_192_grp_fu_559_p_ce;
    end else begin
        grp_fu_559_ce = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state15)) begin
        grp_fu_559_p0 = grp_Application_Pipeline_VITIS_LOOP_197_12_VITIS_LOOP_199_13_fu_221_grp_fu_559_p_din0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        grp_fu_559_p0 = grp_Application_Pipeline_VITIS_LOOP_85_2_VITIS_LOOP_87_3_fu_192_grp_fu_559_p_din0;
    end else begin
        grp_fu_559_p0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state15)) begin
        grp_fu_559_p1 = grp_Application_Pipeline_VITIS_LOOP_197_12_VITIS_LOOP_199_13_fu_221_grp_fu_559_p_din1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        grp_fu_559_p1 = grp_Application_Pipeline_VITIS_LOOP_85_2_VITIS_LOOP_87_3_fu_192_grp_fu_559_p_din1;
    end else begin
        grp_fu_559_p1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state15)) begin
        grp_fu_563_ce = grp_Application_Pipeline_VITIS_LOOP_197_12_VITIS_LOOP_199_13_fu_221_grp_fu_563_p_ce;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        grp_fu_563_ce = grp_Application_Pipeline_VITIS_LOOP_85_2_VITIS_LOOP_87_3_fu_192_grp_fu_563_p_ce;
    end else begin
        grp_fu_563_ce = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state15)) begin
        grp_fu_563_p0 = grp_Application_Pipeline_VITIS_LOOP_197_12_VITIS_LOOP_199_13_fu_221_grp_fu_563_p_din0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        grp_fu_563_p0 = grp_Application_Pipeline_VITIS_LOOP_85_2_VITIS_LOOP_87_3_fu_192_grp_fu_563_p_din0;
    end else begin
        grp_fu_563_p0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state45)) begin
        grp_fu_566_ce = grp_Application_Pipeline_VITIS_LOOP_216_14_VITIS_LOOP_217_15_fu_226_grp_fu_566_p_ce;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        grp_fu_566_ce = grp_Application_Pipeline_VITIS_LOOP_100_4_VITIS_LOOP_102_5_fu_197_grp_fu_566_p_ce;
    end else begin
        grp_fu_566_ce = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state45)) begin
        grp_fu_566_p0 = grp_Application_Pipeline_VITIS_LOOP_216_14_VITIS_LOOP_217_15_fu_226_grp_fu_566_p_din0;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        grp_fu_566_p0 = grp_Application_Pipeline_VITIS_LOOP_100_4_VITIS_LOOP_102_5_fu_197_grp_fu_566_p_din0;
    end else begin
        grp_fu_566_p0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state45)) begin
        grp_p_hls_fptosi_float_i32_fu_180_ap_ce = grp_Application_Pipeline_VITIS_LOOP_216_14_VITIS_LOOP_217_15_fu_226_grp_p_hls_fptosi_float_i32_fu_180_p_ce;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        grp_p_hls_fptosi_float_i32_fu_180_ap_ce = grp_Application_Pipeline_VITIS_LOOP_100_4_VITIS_LOOP_102_5_fu_197_grp_p_hls_fptosi_float_i32_fu_180_p_ce;
    end else if ((((grp_Application_Pipeline_VITIS_LOOP_61_1_fu_172_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state2)) | ((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)))) begin
        grp_p_hls_fptosi_float_i32_fu_180_ap_ce = 1'b1;
    end else begin
        grp_p_hls_fptosi_float_i32_fu_180_ap_ce = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state45)) begin
        grp_p_hls_fptosi_float_i32_fu_180_x = grp_Application_Pipeline_VITIS_LOOP_216_14_VITIS_LOOP_217_15_fu_226_grp_p_hls_fptosi_float_i32_fu_180_p_din1;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        grp_p_hls_fptosi_float_i32_fu_180_x = grp_Application_Pipeline_VITIS_LOOP_100_4_VITIS_LOOP_102_5_fu_197_grp_p_hls_fptosi_float_i32_fu_180_p_din1;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        grp_p_hls_fptosi_float_i32_fu_180_x = amount1;
    end else begin
        grp_p_hls_fptosi_float_i32_fu_180_x = 'bx;
    end
end

always @ (*) begin
    if ((((grp_Application_Pipeline_VITIS_LOOP_61_1_fu_172_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state2)) | ((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)))) begin
        grp_p_hls_fptosi_float_i32_fu_186_ap_ce = 1'b1;
    end else begin
        grp_p_hls_fptosi_float_i32_fu_186_ap_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state45) & (icmp_ln212_reg_546 == 1'd0))) begin
        image_address0 = grp_Application_Pipeline_VITIS_LOOP_216_14_VITIS_LOOP_217_15_fu_226_image_r_address0;
    end else if (((1'b1 == ap_CS_fsm_state15) & (icmp_ln195_reg_542 == 1'd0))) begin
        image_address0 = grp_Application_Pipeline_VITIS_LOOP_197_12_VITIS_LOOP_199_13_fu_221_image_r_address0;
    end else if (((1'b1 == ap_CS_fsm_state13) & (icmp_ln182_reg_538 == 1'd0))) begin
        image_address0 = grp_Application_Pipeline_VITIS_LOOP_184_10_VITIS_LOOP_186_11_fu_216_image_r_address0;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        image_address0 = grp_Application_Pipeline_VITIS_LOOP_170_9_fu_210_image_r_address0;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        image_address0 = grp_Application_Pipeline_VITIS_LOOP_145_7_fu_204_image_r_address0;
    end else if (((1'b1 == ap_CS_fsm_state8) & (icmp_ln98_reg_475 == 1'd0))) begin
        image_address0 = grp_Application_Pipeline_VITIS_LOOP_100_4_VITIS_LOOP_102_5_fu_197_image_r_address0;
    end else if (((1'b1 == ap_CS_fsm_state4) & (icmp_ln83_reg_471 == 1'd0))) begin
        image_address0 = grp_Application_Pipeline_VITIS_LOOP_85_2_VITIS_LOOP_87_3_fu_192_image_r_address0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        image_address0 = grp_Application_Pipeline_VITIS_LOOP_61_1_fu_172_image_r_address0;
    end else begin
        image_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state45) & (icmp_ln212_reg_546 == 1'd0))) begin
        image_address1 = grp_Application_Pipeline_VITIS_LOOP_216_14_VITIS_LOOP_217_15_fu_226_image_r_address1;
    end else if (((1'b1 == ap_CS_fsm_state15) & (icmp_ln195_reg_542 == 1'd0))) begin
        image_address1 = grp_Application_Pipeline_VITIS_LOOP_197_12_VITIS_LOOP_199_13_fu_221_image_r_address1;
    end else if (((1'b1 == ap_CS_fsm_state13) & (icmp_ln182_reg_538 == 1'd0))) begin
        image_address1 = grp_Application_Pipeline_VITIS_LOOP_184_10_VITIS_LOOP_186_11_fu_216_image_r_address1;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        image_address1 = grp_Application_Pipeline_VITIS_LOOP_170_9_fu_210_image_r_address1;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        image_address1 = grp_Application_Pipeline_VITIS_LOOP_145_7_fu_204_image_r_address1;
    end else if (((1'b1 == ap_CS_fsm_state8) & (icmp_ln98_reg_475 == 1'd0))) begin
        image_address1 = grp_Application_Pipeline_VITIS_LOOP_100_4_VITIS_LOOP_102_5_fu_197_image_r_address1;
    end else if (((1'b1 == ap_CS_fsm_state4) & (icmp_ln83_reg_471 == 1'd0))) begin
        image_address1 = grp_Application_Pipeline_VITIS_LOOP_85_2_VITIS_LOOP_87_3_fu_192_image_r_address1;
    end else begin
        image_address1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state45) & (icmp_ln212_reg_546 == 1'd0))) begin
        image_ce0 = grp_Application_Pipeline_VITIS_LOOP_216_14_VITIS_LOOP_217_15_fu_226_image_r_ce0;
    end else if (((1'b1 == ap_CS_fsm_state15) & (icmp_ln195_reg_542 == 1'd0))) begin
        image_ce0 = grp_Application_Pipeline_VITIS_LOOP_197_12_VITIS_LOOP_199_13_fu_221_image_r_ce0;
    end else if (((1'b1 == ap_CS_fsm_state13) & (icmp_ln182_reg_538 == 1'd0))) begin
        image_ce0 = grp_Application_Pipeline_VITIS_LOOP_184_10_VITIS_LOOP_186_11_fu_216_image_r_ce0;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        image_ce0 = grp_Application_Pipeline_VITIS_LOOP_170_9_fu_210_image_r_ce0;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        image_ce0 = grp_Application_Pipeline_VITIS_LOOP_145_7_fu_204_image_r_ce0;
    end else if (((1'b1 == ap_CS_fsm_state8) & (icmp_ln98_reg_475 == 1'd0))) begin
        image_ce0 = grp_Application_Pipeline_VITIS_LOOP_100_4_VITIS_LOOP_102_5_fu_197_image_r_ce0;
    end else if (((1'b1 == ap_CS_fsm_state4) & (icmp_ln83_reg_471 == 1'd0))) begin
        image_ce0 = grp_Application_Pipeline_VITIS_LOOP_85_2_VITIS_LOOP_87_3_fu_192_image_r_ce0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        image_ce0 = grp_Application_Pipeline_VITIS_LOOP_61_1_fu_172_image_r_ce0;
    end else begin
        image_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state45) & (icmp_ln212_reg_546 == 1'd0))) begin
        image_ce1 = grp_Application_Pipeline_VITIS_LOOP_216_14_VITIS_LOOP_217_15_fu_226_image_r_ce1;
    end else if (((1'b1 == ap_CS_fsm_state15) & (icmp_ln195_reg_542 == 1'd0))) begin
        image_ce1 = grp_Application_Pipeline_VITIS_LOOP_197_12_VITIS_LOOP_199_13_fu_221_image_r_ce1;
    end else if (((1'b1 == ap_CS_fsm_state13) & (icmp_ln182_reg_538 == 1'd0))) begin
        image_ce1 = grp_Application_Pipeline_VITIS_LOOP_184_10_VITIS_LOOP_186_11_fu_216_image_r_ce1;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        image_ce1 = grp_Application_Pipeline_VITIS_LOOP_170_9_fu_210_image_r_ce1;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        image_ce1 = grp_Application_Pipeline_VITIS_LOOP_145_7_fu_204_image_r_ce1;
    end else if (((1'b1 == ap_CS_fsm_state8) & (icmp_ln98_reg_475 == 1'd0))) begin
        image_ce1 = grp_Application_Pipeline_VITIS_LOOP_100_4_VITIS_LOOP_102_5_fu_197_image_r_ce1;
    end else if (((1'b1 == ap_CS_fsm_state4) & (icmp_ln83_reg_471 == 1'd0))) begin
        image_ce1 = grp_Application_Pipeline_VITIS_LOOP_85_2_VITIS_LOOP_87_3_fu_192_image_r_ce1;
    end else begin
        image_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state45) & (icmp_ln212_reg_546 == 1'd0))) begin
        image_d0 = grp_Application_Pipeline_VITIS_LOOP_216_14_VITIS_LOOP_217_15_fu_226_image_r_d0;
    end else if (((1'b1 == ap_CS_fsm_state15) & (icmp_ln195_reg_542 == 1'd0))) begin
        image_d0 = grp_Application_Pipeline_VITIS_LOOP_197_12_VITIS_LOOP_199_13_fu_221_image_r_d0;
    end else if (((1'b1 == ap_CS_fsm_state13) & (icmp_ln182_reg_538 == 1'd0))) begin
        image_d0 = grp_Application_Pipeline_VITIS_LOOP_184_10_VITIS_LOOP_186_11_fu_216_image_r_d0;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        image_d0 = grp_Application_Pipeline_VITIS_LOOP_170_9_fu_210_image_r_d0;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        image_d0 = grp_Application_Pipeline_VITIS_LOOP_145_7_fu_204_image_r_d0;
    end else if (((1'b1 == ap_CS_fsm_state8) & (icmp_ln98_reg_475 == 1'd0))) begin
        image_d0 = grp_Application_Pipeline_VITIS_LOOP_100_4_VITIS_LOOP_102_5_fu_197_image_r_d0;
    end else if (((1'b1 == ap_CS_fsm_state4) & (icmp_ln83_reg_471 == 1'd0))) begin
        image_d0 = grp_Application_Pipeline_VITIS_LOOP_85_2_VITIS_LOOP_87_3_fu_192_image_r_d0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        image_d0 = grp_Application_Pipeline_VITIS_LOOP_61_1_fu_172_image_r_d0;
    end else begin
        image_d0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state45) & (icmp_ln212_reg_546 == 1'd0))) begin
        image_d1 = grp_Application_Pipeline_VITIS_LOOP_216_14_VITIS_LOOP_217_15_fu_226_image_r_d1;
    end else if (((1'b1 == ap_CS_fsm_state15) & (icmp_ln195_reg_542 == 1'd0))) begin
        image_d1 = grp_Application_Pipeline_VITIS_LOOP_197_12_VITIS_LOOP_199_13_fu_221_image_r_d1;
    end else if (((1'b1 == ap_CS_fsm_state13) & (icmp_ln182_reg_538 == 1'd0))) begin
        image_d1 = grp_Application_Pipeline_VITIS_LOOP_184_10_VITIS_LOOP_186_11_fu_216_image_r_d1;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        image_d1 = grp_Application_Pipeline_VITIS_LOOP_145_7_fu_204_image_r_d1;
    end else if (((1'b1 == ap_CS_fsm_state8) & (icmp_ln98_reg_475 == 1'd0))) begin
        image_d1 = grp_Application_Pipeline_VITIS_LOOP_100_4_VITIS_LOOP_102_5_fu_197_image_r_d1;
    end else if (((1'b1 == ap_CS_fsm_state4) & (icmp_ln83_reg_471 == 1'd0))) begin
        image_d1 = grp_Application_Pipeline_VITIS_LOOP_85_2_VITIS_LOOP_87_3_fu_192_image_r_d1;
    end else begin
        image_d1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state45) & (icmp_ln212_reg_546 == 1'd0))) begin
        image_we0 = grp_Application_Pipeline_VITIS_LOOP_216_14_VITIS_LOOP_217_15_fu_226_image_r_we0;
    end else if (((1'b1 == ap_CS_fsm_state15) & (icmp_ln195_reg_542 == 1'd0))) begin
        image_we0 = grp_Application_Pipeline_VITIS_LOOP_197_12_VITIS_LOOP_199_13_fu_221_image_r_we0;
    end else if (((1'b1 == ap_CS_fsm_state13) & (icmp_ln182_reg_538 == 1'd0))) begin
        image_we0 = grp_Application_Pipeline_VITIS_LOOP_184_10_VITIS_LOOP_186_11_fu_216_image_r_we0;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        image_we0 = grp_Application_Pipeline_VITIS_LOOP_170_9_fu_210_image_r_we0;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        image_we0 = grp_Application_Pipeline_VITIS_LOOP_145_7_fu_204_image_r_we0;
    end else if (((1'b1 == ap_CS_fsm_state8) & (icmp_ln98_reg_475 == 1'd0))) begin
        image_we0 = grp_Application_Pipeline_VITIS_LOOP_100_4_VITIS_LOOP_102_5_fu_197_image_r_we0;
    end else if (((1'b1 == ap_CS_fsm_state4) & (icmp_ln83_reg_471 == 1'd0))) begin
        image_we0 = grp_Application_Pipeline_VITIS_LOOP_85_2_VITIS_LOOP_87_3_fu_192_image_r_we0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        image_we0 = grp_Application_Pipeline_VITIS_LOOP_61_1_fu_172_image_r_we0;
    end else begin
        image_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state45) & (icmp_ln212_reg_546 == 1'd0))) begin
        image_we1 = grp_Application_Pipeline_VITIS_LOOP_216_14_VITIS_LOOP_217_15_fu_226_image_r_we1;
    end else if (((1'b1 == ap_CS_fsm_state15) & (icmp_ln195_reg_542 == 1'd0))) begin
        image_we1 = grp_Application_Pipeline_VITIS_LOOP_197_12_VITIS_LOOP_199_13_fu_221_image_r_we1;
    end else if (((1'b1 == ap_CS_fsm_state13) & (icmp_ln182_reg_538 == 1'd0))) begin
        image_we1 = grp_Application_Pipeline_VITIS_LOOP_184_10_VITIS_LOOP_186_11_fu_216_image_r_we1;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        image_we1 = grp_Application_Pipeline_VITIS_LOOP_145_7_fu_204_image_r_we1;
    end else if (((1'b1 == ap_CS_fsm_state8) & (icmp_ln98_reg_475 == 1'd0))) begin
        image_we1 = grp_Application_Pipeline_VITIS_LOOP_100_4_VITIS_LOOP_102_5_fu_197_image_r_we1;
    end else if (((1'b1 == ap_CS_fsm_state4) & (icmp_ln83_reg_471 == 1'd0))) begin
        image_we1 = grp_Application_Pipeline_VITIS_LOOP_85_2_VITIS_LOOP_87_3_fu_192_image_r_we1;
    end else begin
        image_we1 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((grp_Application_Pipeline_VITIS_LOOP_61_1_fu_172_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state2) & (icmp_ln83_fu_266_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else if (((grp_Application_Pipeline_VITIS_LOOP_61_1_fu_172_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state2) & (icmp_ln83_fu_266_p2 == 1'd0))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            if (((1'b0 == ap_block_state4_on_subcall_done) & (1'b1 == ap_CS_fsm_state4) & (icmp_ln98_fu_272_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end else if (((1'b0 == ap_block_state4_on_subcall_done) & (1'b1 == ap_CS_fsm_state4) & (icmp_ln98_fu_272_p2 == 1'd0))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            if (((1'b0 == ap_block_state8_on_subcall_done) & (1'b1 == ap_CS_fsm_state8) & (icmp_ln137_fu_325_p2 == 1'd0))) begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end else if (((1'b0 == ap_block_state8_on_subcall_done) & (1'b1 == ap_CS_fsm_state8) & (icmp_ln137_fu_325_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state11;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end
        end
        ap_ST_fsm_state9 : begin
            if (((1'b1 == ap_CS_fsm_state9) & ((icmp_ln141_fu_358_p2 == 1'd1) | (icmp_ln139_reg_493 == 1'd1)))) begin
                ap_NS_fsm = ap_ST_fsm_state11;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end
        end
        ap_ST_fsm_state10 : begin
            if (((grp_Application_Pipeline_VITIS_LOOP_145_7_fu_204_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state10))) begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end
        end
        ap_ST_fsm_state11 : begin
            if (((1'b1 == ap_CS_fsm_state11) & ((icmp_ln137_reg_489 == 1'd1) | ((icmp_ln166_fu_394_p2 == 1'd1) | (icmp_ln164_reg_519 == 1'd1))))) begin
                ap_NS_fsm = ap_ST_fsm_state13;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state12;
            end
        end
        ap_ST_fsm_state12 : begin
            if (((grp_Application_Pipeline_VITIS_LOOP_170_9_fu_210_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state12))) begin
                ap_NS_fsm = ap_ST_fsm_state11;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state12;
            end
        end
        ap_ST_fsm_state13 : begin
            if (((1'b0 == ap_block_state13_on_subcall_done) & (1'b1 == ap_CS_fsm_state13) & (icmp_ln195_fu_416_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state15;
            end else if (((1'b0 == ap_block_state13_on_subcall_done) & (1'b1 == ap_CS_fsm_state13) & (icmp_ln195_fu_416_p2 == 1'd0))) begin
                ap_NS_fsm = ap_ST_fsm_state14;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state13;
            end
        end
        ap_ST_fsm_state14 : begin
            ap_NS_fsm = ap_ST_fsm_state15;
        end
        ap_ST_fsm_state15 : begin
            if (((1'b0 == ap_block_state15_on_subcall_done) & (1'b1 == ap_CS_fsm_state15) & (icmp_ln212_fu_421_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state45;
            end else if (((1'b0 == ap_block_state15_on_subcall_done) & (1'b1 == ap_CS_fsm_state15) & (icmp_ln212_fu_421_p2 == 1'd0))) begin
                ap_NS_fsm = ap_ST_fsm_state16;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state15;
            end
        end
        ap_ST_fsm_state16 : begin
            ap_NS_fsm = ap_ST_fsm_state17;
        end
        ap_ST_fsm_state17 : begin
            ap_NS_fsm = ap_ST_fsm_state18;
        end
        ap_ST_fsm_state18 : begin
            ap_NS_fsm = ap_ST_fsm_state19;
        end
        ap_ST_fsm_state19 : begin
            ap_NS_fsm = ap_ST_fsm_state20;
        end
        ap_ST_fsm_state20 : begin
            ap_NS_fsm = ap_ST_fsm_state21;
        end
        ap_ST_fsm_state21 : begin
            ap_NS_fsm = ap_ST_fsm_state22;
        end
        ap_ST_fsm_state22 : begin
            ap_NS_fsm = ap_ST_fsm_state23;
        end
        ap_ST_fsm_state23 : begin
            ap_NS_fsm = ap_ST_fsm_state24;
        end
        ap_ST_fsm_state24 : begin
            ap_NS_fsm = ap_ST_fsm_state25;
        end
        ap_ST_fsm_state25 : begin
            ap_NS_fsm = ap_ST_fsm_state26;
        end
        ap_ST_fsm_state26 : begin
            ap_NS_fsm = ap_ST_fsm_state27;
        end
        ap_ST_fsm_state27 : begin
            ap_NS_fsm = ap_ST_fsm_state28;
        end
        ap_ST_fsm_state28 : begin
            ap_NS_fsm = ap_ST_fsm_state29;
        end
        ap_ST_fsm_state29 : begin
            ap_NS_fsm = ap_ST_fsm_state30;
        end
        ap_ST_fsm_state30 : begin
            ap_NS_fsm = ap_ST_fsm_state31;
        end
        ap_ST_fsm_state31 : begin
            ap_NS_fsm = ap_ST_fsm_state32;
        end
        ap_ST_fsm_state32 : begin
            ap_NS_fsm = ap_ST_fsm_state33;
        end
        ap_ST_fsm_state33 : begin
            ap_NS_fsm = ap_ST_fsm_state34;
        end
        ap_ST_fsm_state34 : begin
            ap_NS_fsm = ap_ST_fsm_state35;
        end
        ap_ST_fsm_state35 : begin
            ap_NS_fsm = ap_ST_fsm_state36;
        end
        ap_ST_fsm_state36 : begin
            ap_NS_fsm = ap_ST_fsm_state37;
        end
        ap_ST_fsm_state37 : begin
            ap_NS_fsm = ap_ST_fsm_state38;
        end
        ap_ST_fsm_state38 : begin
            ap_NS_fsm = ap_ST_fsm_state39;
        end
        ap_ST_fsm_state39 : begin
            ap_NS_fsm = ap_ST_fsm_state40;
        end
        ap_ST_fsm_state40 : begin
            ap_NS_fsm = ap_ST_fsm_state41;
        end
        ap_ST_fsm_state41 : begin
            ap_NS_fsm = ap_ST_fsm_state42;
        end
        ap_ST_fsm_state42 : begin
            ap_NS_fsm = ap_ST_fsm_state43;
        end
        ap_ST_fsm_state43 : begin
            ap_NS_fsm = ap_ST_fsm_state44;
        end
        ap_ST_fsm_state44 : begin
            ap_NS_fsm = ap_ST_fsm_state45;
        end
        ap_ST_fsm_state45 : begin
            if (((1'b0 == ap_block_state45_on_subcall_done) & (1'b1 == ap_CS_fsm_state45))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state45;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln141_1_fu_352_p2 = (phi_mul_fu_112 + 12'd90);

assign add_ln141_fu_364_p2 = (i_fu_116 + 5'd1);

assign add_ln166_fu_400_p2 = (i_3_fu_120 + 7'd1);

assign amount1_to_int_fu_277_p1 = amount1;

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state12 = ap_CS_fsm[32'd11];

assign ap_CS_fsm_state13 = ap_CS_fsm[32'd12];

assign ap_CS_fsm_state14 = ap_CS_fsm[32'd13];

assign ap_CS_fsm_state15 = ap_CS_fsm[32'd14];

assign ap_CS_fsm_state16 = ap_CS_fsm[32'd15];

assign ap_CS_fsm_state17 = ap_CS_fsm[32'd16];

assign ap_CS_fsm_state18 = ap_CS_fsm[32'd17];

assign ap_CS_fsm_state19 = ap_CS_fsm[32'd18];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state20 = ap_CS_fsm[32'd19];

assign ap_CS_fsm_state21 = ap_CS_fsm[32'd20];

assign ap_CS_fsm_state22 = ap_CS_fsm[32'd21];

assign ap_CS_fsm_state23 = ap_CS_fsm[32'd22];

assign ap_CS_fsm_state24 = ap_CS_fsm[32'd23];

assign ap_CS_fsm_state25 = ap_CS_fsm[32'd24];

assign ap_CS_fsm_state26 = ap_CS_fsm[32'd25];

assign ap_CS_fsm_state27 = ap_CS_fsm[32'd26];

assign ap_CS_fsm_state28 = ap_CS_fsm[32'd27];

assign ap_CS_fsm_state29 = ap_CS_fsm[32'd28];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state44 = ap_CS_fsm[32'd43];

assign ap_CS_fsm_state45 = ap_CS_fsm[32'd44];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

always @ (*) begin
    ap_block_state13_on_subcall_done = ((grp_Application_Pipeline_VITIS_LOOP_184_10_VITIS_LOOP_186_11_fu_216_ap_done == 1'b0) & (icmp_ln182_reg_538 == 1'd0));
end

always @ (*) begin
    ap_block_state15_on_subcall_done = ((grp_Application_Pipeline_VITIS_LOOP_197_12_VITIS_LOOP_199_13_fu_221_ap_done == 1'b0) & (icmp_ln195_reg_542 == 1'd0));
end

always @ (*) begin
    ap_block_state45_on_subcall_done = ((grp_Application_Pipeline_VITIS_LOOP_216_14_VITIS_LOOP_217_15_fu_226_ap_done == 1'b0) & (icmp_ln212_reg_546 == 1'd0));
end

always @ (*) begin
    ap_block_state4_on_subcall_done = ((grp_Application_Pipeline_VITIS_LOOP_85_2_VITIS_LOOP_87_3_fu_192_ap_done == 1'b0) & (icmp_ln83_reg_471 == 1'd0));
end

always @ (*) begin
    ap_block_state8_on_subcall_done = ((grp_Application_Pipeline_VITIS_LOOP_100_4_VITIS_LOOP_102_5_fu_197_ap_done == 1'b0) & (icmp_ln98_reg_475 == 1'd0));
end

assign ap_return = 32'd0;

assign brmerge_demorgan_fu_318_p2 = (grp_fu_255_p2 & empty_67_fu_312_p2);

assign empty_66_fu_306_p2 = (notrhs_fu_300_p2 | notlhs_fu_294_p2);

assign empty_67_fu_312_p2 = (grp_fu_250_p2 & empty_66_fu_306_p2);

assign empty_fu_290_p1 = amount1_to_int_fu_277_p1[22:0];

assign grp_Application_Pipeline_VITIS_LOOP_100_4_VITIS_LOOP_102_5_fu_197_ap_start = grp_Application_Pipeline_VITIS_LOOP_100_4_VITIS_LOOP_102_5_fu_197_ap_start_reg;

assign grp_Application_Pipeline_VITIS_LOOP_145_7_fu_204_ap_start = grp_Application_Pipeline_VITIS_LOOP_145_7_fu_204_ap_start_reg;

assign grp_Application_Pipeline_VITIS_LOOP_170_9_fu_210_ap_start = grp_Application_Pipeline_VITIS_LOOP_170_9_fu_210_ap_start_reg;

assign grp_Application_Pipeline_VITIS_LOOP_184_10_VITIS_LOOP_186_11_fu_216_ap_start = grp_Application_Pipeline_VITIS_LOOP_184_10_VITIS_LOOP_186_11_fu_216_ap_start_reg;

assign grp_Application_Pipeline_VITIS_LOOP_197_12_VITIS_LOOP_199_13_fu_221_ap_start = grp_Application_Pipeline_VITIS_LOOP_197_12_VITIS_LOOP_199_13_fu_221_ap_start_reg;

assign grp_Application_Pipeline_VITIS_LOOP_216_14_VITIS_LOOP_217_15_fu_226_ap_start = grp_Application_Pipeline_VITIS_LOOP_216_14_VITIS_LOOP_217_15_fu_226_ap_start_reg;

assign grp_Application_Pipeline_VITIS_LOOP_61_1_fu_172_ap_start = grp_Application_Pipeline_VITIS_LOOP_61_1_fu_172_ap_start_reg;

assign grp_Application_Pipeline_VITIS_LOOP_85_2_VITIS_LOOP_87_3_fu_192_ap_start = grp_Application_Pipeline_VITIS_LOOP_85_2_VITIS_LOOP_87_3_fu_192_ap_start_reg;

assign icmp_ln137_fu_325_p2 = ((flip == 32'd0) ? 1'b1 : 1'b0);

assign icmp_ln139_fu_330_p2 = ((flipHorizontal_reg_461 == 32'd0) ? 1'b1 : 1'b0);

assign icmp_ln141_fu_358_p2 = ((i_fu_116 == 5'd23) ? 1'b1 : 1'b0);

assign icmp_ln164_fu_380_p2 = ((flipVertical_reg_466 == 32'd0) ? 1'b1 : 1'b0);

assign icmp_ln166_fu_394_p2 = ((i_3_fu_120 == 7'd90) ? 1'b1 : 1'b0);

assign icmp_ln182_fu_411_p2 = ((invert == 32'd0) ? 1'b1 : 1'b0);

assign icmp_ln195_fu_416_p2 = ((sepia == 32'd0) ? 1'b1 : 1'b0);

assign icmp_ln212_fu_421_p2 = ((sharpen == 32'd0) ? 1'b1 : 1'b0);

assign icmp_ln83_fu_266_p2 = ((grayscale == 32'd0) ? 1'b1 : 1'b0);

assign icmp_ln98_fu_272_p2 = ((brighten == 32'd0) ? 1'b1 : 1'b0);

assign notlhs_fu_294_p2 = ((tmp_fu_280_p4 != 8'd255) ? 1'b1 : 1'b0);

assign notrhs_fu_300_p2 = ((empty_fu_290_p1 == 23'd0) ? 1'b1 : 1'b0);

assign tmp_fu_280_p4 = {{amount1_to_int_fu_277_p1[30:23]}};

endmodule //Application
